// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-agentic Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const STATE_IDLE: u8 = 0;
pub const STATE_PLANNING: u8 = 1;
pub const STATE_ACTING: u8 = 2;
pub const STATE_OBSERVING: u8 = 3;
pub const STATE_REFLECTING: u8 = 4;
pub const STATE_BLOCKED: u8 = 5;
pub const STATE_TERMINATED: u8 = 6;
pub const TOOL_EXECUTE: u8 = 0;
pub const TOOL_QUERY: u8 = 1;
pub const TOOL_TRANSFORM: u8 = 2;
pub const TOOL_COMMUNICATE: u8 = 3;
pub const TOOL_DELEGATE: u8 = 4;
pub const TOOL_ESCALATE: u8 = 5;
pub const STEP_ACTION: u8 = 0;
pub const STEP_CONDITION: u8 = 1;
pub const STEP_LOOP: u8 = 2;
pub const STEP_BRANCH: u8 = 3;
pub const STEP_PARALLEL: u8 = 4;
pub const STEP_CHECKPOINT: u8 = 5;
pub const STEP_ROLLBACK: u8 = 6;
pub const COORD_SOLO: u8 = 0;
pub const COORD_COLLABORATIVE: u8 = 1;
pub const COORD_COMPETITIVE: u8 = 2;
pub const COORD_HIERARCHICAL: u8 = 3;
pub const COORD_SWARM: u8 = 4;
pub const COORD_CONSENSUS: u8 = 5;
pub const SAFETY_APPROVED: u8 = 0;
pub const SAFETY_DENIED: u8 = 1;
pub const SAFETY_ESCALATED: u8 = 2;
pub const SAFETY_TIMEOUT: u8 = 3;
pub const SAFETY_SANDBOXED: u8 = 4;
pub const SAFETY_HUMAN_REQUIRED: u8 = 5;
pub const MEM_WORKING: u8 = 0;
pub const MEM_EPISODIC: u8 = 1;
pub const MEM_SEMANTIC: u8 = 2;
pub const MEM_PROCEDURAL: u8 = 3;
pub const MEM_SHARED: u8 = 4;
pub const ERR_OK: u8 = 0;
pub const ERR_INVALID_SLOT: u8 = 1;
pub const ERR_NOT_ACTIVE: u8 = 2;
pub const ERR_INVALID_TRANSITION: u8 = 3;
pub const ERR_BLOCKED: u8 = 4;
pub const ERR_TOOL_LIMIT_EXCEEDED: u8 = 5;
pub const ERR_PLAN_DEPTH_EXCEEDED: u8 = 6;
pub const ERR_SAFETY_DENIED: u8 = 7;
