// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-caldav Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const COMP_VEVENT: u8 = 0;
pub const COMP_VTODO: u8 = 1;
pub const COMP_VJOURNAL: u8 = 2;
pub const COMP_VFREEBUSY: u8 = 3;
pub const METHOD_GET: u8 = 0;
pub const METHOD_PUT: u8 = 1;
pub const METHOD_DELETE: u8 = 2;
pub const METHOD_PROPFIND: u8 = 3;
pub const METHOD_PROPPATCH: u8 = 4;
pub const METHOD_REPORT: u8 = 5;
pub const METHOD_MKCALENDAR: u8 = 6;
pub const SCHED_NEEDS_ACTION: u8 = 0;
pub const SCHED_ACCEPTED: u8 = 1;
pub const SCHED_DECLINED: u8 = 2;
pub const SCHED_TENTATIVE: u8 = 3;
pub const SCHED_DELEGATED: u8 = 4;
pub const ERR_VALID_CALENDAR_DATA: u8 = 0;
pub const ERR_NO_RESOURCE_TYPE_CHANGE: u8 = 1;
pub const ERR_SUPPORTED_COMPONENT_MISMATCH: u8 = 2;
pub const ERR_MAX_RESOURCE_SIZE: u8 = 3;
pub const ERR_UID_CONFLICT: u8 = 4;
pub const ERR_PRECONDITION_FAILED: u8 = 5;
pub const SRV_IDLE: u8 = 0;
pub const SRV_BOUND: u8 = 1;
pub const SRV_SERVING: u8 = 2;
pub const SRV_SCHEDULING: u8 = 3;
pub const SRV_SHUTDOWN: u8 = 4;
