// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-authserver Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const AUTHM_PASSWORD: u8 = 0;
pub const AUTHM_CERTIFICATE: u8 = 1;
pub const AUTHM_OAUTH2: u8 = 2;
pub const AUTHM_SAML: u8 = 3;
pub const AUTHM_FIDO2: u8 = 4;
pub const AUTHM_KERBEROS: u8 = 5;
pub const AUTHM_LDAP: u8 = 6;
pub const AUTHM_RADIUS: u8 = 7;
pub const TOKEN_ACCESS: u8 = 0;
pub const TOKEN_REFRESH: u8 = 1;
pub const TOKEN_ID: u8 = 2;
pub const TOKEN_API: u8 = 3;
pub const RESULT_SUCCESS: u8 = 0;
pub const RESULT_INVALID_CREDENTIALS: u8 = 1;
pub const RESULT_ACCOUNT_LOCKED: u8 = 2;
pub const RESULT_ACCOUNT_EXPIRED: u8 = 3;
pub const RESULT_MFA_REQUIRED: u8 = 4;
pub const RESULT_IP_BLOCKED: u8 = 5;
pub const MFA_TOTP: u8 = 0;
pub const MFA_SMS: u8 = 1;
pub const MFA_PUSH: u8 = 2;
pub const MFA_FIDO2_MFA: u8 = 3;
pub const MFA_EMAIL: u8 = 4;
pub const SESSION_ACTIVE: u8 = 0;
pub const SESSION_EXPIRED: u8 = 1;
pub const SESSION_REVOKED: u8 = 2;
pub const SESSION_LOCKED: u8 = 3;
