# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
#
# Top-level module for proven-servers Julia bindings.
#
# Provides type-safe Julia wrappers around the Zig FFI shared libraries
# for all proven-servers protocols. Each protocol is exposed as a
# submodule with @enum types matching the Idris2 ABI and ccall
# declarations for the C-ABI functions.
#
# Usage:
#   using ProvenServers
#   ctx = Httpd.create_context()
#   Httpd.destroy_context(ctx)

module ProvenServers

include("error.jl")

# --- Core protocols (original 10) ---
include("Httpd.jl")
include("Dns.jl")
include("Smtp.jl")
include("Ssh.jl")
include("Mqtt.jl")
include("Ftp.jl")
include("Firewall.jl")
include("Graphql.jl")
include("Grpc.jl")
include("Websocket.jl")

# --- Extended protocols (44 additional) ---
include("Agentic.jl")
include("Airgap.jl")
include("Amqp.jl")
include("Apiserver.jl")
include("Appserver.jl")
include("Authserver.jl")
include("Backup.jl")
include("Bfd.jl")
include("Bgp.jl")
include("Ca.jl")
include("Cache.jl")
include("Caldav.jl")
include("Carddav.jl")
include("Chat.jl")
include("Cli.jl")
include("Coap.jl")
include("Configmgmt.jl")
include("Container.jl")
include("Ctlog.jl")
include("Dbserver.jl")
include("Dds.jl")
include("Deception.jl")
include("Dhcp.jl")
include("Diode.jl")
include("Doh.jl")
include("Doq.jl")
include("Dot.jl")
include("Federation.jl")
include("Fileserver.jl")
include("Gameserver.jl")
include("Git.jl")
include("Graphdb.jl")
include("Hardened.jl")
include("Honeypot.jl")
include("Ids.jl")
include("Imap.jl")
include("Irc.jl")
include("Kerberos.jl")
include("Kms.jl")
include("Ldap.jl")
include("Ldp.jl")
include("Loadbalancer.jl")
include("Logcollector.jl")
include("Lpd.jl")
include("Mcp.jl")
include("Mdns.jl")
include("Media.jl")
include("Metrics.jl")
include("Modbus.jl")
include("Monitor.jl")
include("Nesy.jl")
include("Netconf.jl")
include("Neurosym.jl")
include("Nfs.jl")
include("Ntp.jl")
include("Nts.jl")
include("Objectstore.jl")
include("Ocsp.jl")
include("Odns.jl")
include("Opcua.jl")
include("Ospf.jl")
include("Pop3.jl")
include("Pqc.jl")
include("Proxy.jl")
include("Ptp.jl")
include("Radius.jl")
include("Rtsp.jl")
include("Sandbox.jl")
include("Sdn.jl")
include("Semweb.jl")
include("Siem.jl")
include("Smb.jl")
include("Snmp.jl")
include("Socks.jl")
include("Sparql.jl")
include("SshBastion.jl")
include("Stun.jl")
include("Syslog.jl")
include("Tacacs.jl")
include("Telnet.jl")
include("Tftp.jl")
include("Triplestore.jl")
include("Virt.jl")
include("Voip.jl")
include("Vpn.jl")
include("Wasm.jl")
include("Xmpp.jl")
include("Zerotrust.jl")

end # module ProvenServers
