// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-modbus Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const FUNC_READ_COILS: u8 = 0;
pub const FUNC_READ_DISCRETE_INPUTS: u8 = 1;
pub const FUNC_READ_HOLDING_REGISTERS: u8 = 2;
pub const FUNC_READ_INPUT_REGISTERS: u8 = 3;
pub const FUNC_WRITE_SINGLE_COIL: u8 = 4;
pub const FUNC_WRITE_SINGLE_REGISTER: u8 = 5;
pub const FUNC_WRITE_MULTIPLE_COILS: u8 = 6;
pub const FUNC_WRITE_MULTIPLE_REGISTERS: u8 = 7;
pub const FUNC_READ_WRITE_MULTIPLE_REGISTERS: u8 = 8;
pub const FUNC_MASK_WRITE_REGISTER: u8 = 9;
pub const EXC_ILLEGAL_FUNCTION: u8 = 0;
pub const EXC_ILLEGAL_DATA_ADDRESS: u8 = 1;
pub const EXC_ILLEGAL_DATA_VALUE: u8 = 2;
pub const EXC_SLAVE_DEVICE_FAILURE: u8 = 3;
pub const EXC_ACKNOWLEDGE: u8 = 4;
pub const EXC_SLAVE_DEVICE_BUSY: u8 = 5;
pub const EXC_MEMORY_PARITY_ERROR: u8 = 6;
pub const EXC_GATEWAY_PATH_UNAVAILABLE: u8 = 7;
pub const EXC_GATEWAY_TARGET_DEVICE_FAILED: u8 = 8;
pub const ROLE_MASTER: u8 = 0;
pub const ROLE_SLAVE: u8 = 1;
pub const GW_IDLE: u8 = 0;
pub const GW_LISTENING: u8 = 1;
pub const GW_PROCESSING: u8 = 2;
pub const GW_ERR: u8 = 3;
pub const GW_STOPPING: u8 = 4;
