// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-imap Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const COMMAND_LOGIN: u8 = 0;
pub const COMMAND_LOGOUT: u8 = 1;
pub const COMMAND_SELECT: u8 = 2;
pub const COMMAND_EXAMINE: u8 = 3;
pub const COMMAND_CREATE: u8 = 4;
pub const COMMAND_DELETE: u8 = 5;
pub const COMMAND_RENAME: u8 = 6;
pub const COMMAND_LIST: u8 = 7;
pub const COMMAND_FETCH: u8 = 8;
pub const COMMAND_STORE: u8 = 9;
pub const COMMAND_SEARCH: u8 = 10;
pub const COMMAND_COPY: u8 = 11;
pub const COMMAND_NOOP: u8 = 12;
pub const COMMAND_CAPABILITY: u8 = 13;
pub const STATE_NOT_AUTHENTICATED: u8 = 0;
pub const STATE_AUTHENTICATED: u8 = 1;
pub const STATE_SELECTED: u8 = 2;
pub const STATE_LOGOUT_STATE: u8 = 3;
pub const FLAG_SEEN: u8 = 0;
pub const FLAG_ANSWERED: u8 = 1;
pub const FLAG_FLAGGED: u8 = 2;
pub const FLAG_DELETED: u8 = 3;
pub const FLAG_DRAFT: u8 = 4;
pub const FLAG_RECENT: u8 = 5;
