// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-dds Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const REL_BEST_EFFORT: u8 = 0;
pub const REL_RELIABLE: u8 = 1;
pub const DUR_VOLATILE: u8 = 0;
pub const DUR_TRANSIENT_LOCAL: u8 = 1;
pub const DUR_TRANSIENT: u8 = 2;
pub const DUR_PERSISTENT: u8 = 3;
pub const HIST_KEEP_LAST: u8 = 0;
pub const HIST_KEEP_ALL: u8 = 1;
pub const OWN_SHARED: u8 = 0;
pub const OWN_EXCLUSIVE: u8 = 1;
pub const ENT_PARTICIPANT: u8 = 0;
pub const ENT_PUBLISHER: u8 = 1;
pub const ENT_SUBSCRIBER: u8 = 2;
pub const ENT_TOPIC: u8 = 3;
pub const ENT_DATA_WRITER: u8 = 4;
pub const ENT_DATA_READER: u8 = 5;
pub const PSTATE_IDLE: u8 = 0;
pub const PSTATE_JOINED: u8 = 1;
pub const PSTATE_PUBLISHING: u8 = 2;
pub const PSTATE_SUBSCRIBING: u8 = 3;
pub const PSTATE_LEAVING: u8 = 4;
