// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-diode Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const DIR_HIGH_TO_LOW: u8 = 0;
pub const DIR_LOW_TO_HIGH: u8 = 1;
pub const PROTO_UDP: u8 = 0;
pub const PROTO_TCP: u8 = 1;
pub const PROTO_FILE_TRANSFER: u8 = 2;
pub const PROTO_SYSLOG: u8 = 3;
pub const PROTO_SNMP: u8 = 4;
pub const XFER_QUEUED: u8 = 0;
pub const XFER_SENDING: u8 = 1;
pub const XFER_CONFIRMING: u8 = 2;
pub const XFER_COMPLETE: u8 = 3;
pub const XFER_FAILED: u8 = 4;
pub const VALID_PASSED: u8 = 0;
pub const VALID_FORMAT_ERROR: u8 = 1;
pub const VALID_SIZE_EXCEEDED: u8 = 2;
pub const VALID_POLICY_BLOCKED: u8 = 3;
pub const INTEG_CRC32: u8 = 0;
pub const INTEG_SHA256: u8 = 1;
pub const INTEG_HMAC: u8 = 2;
pub const GW_IDLE: u8 = 0;
pub const GW_CONFIGURED: u8 = 1;
pub const GW_TRANSFERRING: u8 = 2;
pub const GW_VALIDATING: u8 = 3;
pub const GW_SHUTDOWN: u8 = 4;
