// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-bfd Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const STATE_ADMIN_DOWN: u8 = 0;
pub const STATE_DOWN: u8 = 1;
pub const STATE_INIT: u8 = 2;
pub const STATE_UP: u8 = 3;
pub const DIAG_NO_DIAGNOSTIC: u8 = 0;
pub const DIAG_CONTROL_DETECTION_TIME_EXPIRED: u8 = 1;
pub const DIAG_ECHO_FUNCTION_FAILED: u8 = 2;
pub const DIAG_NEIGHBOR_SIGNALED_SESSION_DOWN: u8 = 3;
pub const DIAG_FORWARDING_PLANE_RESET: u8 = 4;
pub const DIAG_PATH_DOWN: u8 = 5;
pub const DIAG_CONCATENATED_PATH_DOWN: u8 = 6;
pub const DIAG_ADMINISTRATIVELY_DOWN: u8 = 7;
pub const DIAG_REVERSE_CONCATENATED_PATH_DOWN: u8 = 8;
pub const MODE_ASYNC_MODE: u8 = 0;
pub const MODE_DEMAND_MODE: u8 = 1;
pub const SESSION_IDLE: u8 = 0;
pub const SESSION_SS_DOWN: u8 = 1;
pub const SESSION_NEGOTIATING: u8 = 2;
pub const SESSION_ESTABLISHED: u8 = 3;
pub const SESSION_TEARDOWN: u8 = 4;
