// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-carddav Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const PROP_FN: u8 = 0;
pub const PROP_N: u8 = 1;
pub const PROP_EMAIL: u8 = 2;
pub const PROP_TEL: u8 = 3;
pub const PROP_ADR: u8 = 4;
pub const PROP_ORG: u8 = 5;
pub const PROP_PHOTO: u8 = 6;
pub const PROP_URL: u8 = 7;
pub const PROP_NOTE: u8 = 8;
pub const METHOD_GET: u8 = 0;
pub const METHOD_PUT: u8 = 1;
pub const METHOD_DELETE: u8 = 2;
pub const METHOD_PROPFIND: u8 = 3;
pub const METHOD_PROPPATCH: u8 = 4;
pub const METHOD_REPORT: u8 = 5;
pub const METHOD_MKCOL: u8 = 6;
pub const VER_VCARD3: u8 = 0;
pub const VER_VCARD4: u8 = 1;
pub const ERR_VALID_ADDRESS_DATA: u8 = 0;
pub const ERR_NO_RESOURCE_TYPE: u8 = 1;
pub const ERR_MAX_RESOURCE_SIZE: u8 = 2;
pub const ERR_UID_CONFLICT: u8 = 3;
pub const ERR_SUPPORTED_ADDRESS_DATA: u8 = 4;
pub const ERR_PRECONDITION_FAILED: u8 = 5;
pub const STATE_IDLE: u8 = 0;
pub const STATE_BOUND: u8 = 1;
pub const STATE_SERVING: u8 = 2;
pub const STATE_SHUTDOWN: u8 = 3;
