// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-amqp Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const FRAME_METHOD: u8 = 0;
pub const FRAME_HEADER: u8 = 1;
pub const FRAME_BODY: u8 = 2;
pub const FRAME_HEARTBEAT: u8 = 3;
pub const CLASS_CONNECTION: u8 = 0;
pub const CLASS_CHANNEL: u8 = 1;
pub const CLASS_EXCHANGE: u8 = 2;
pub const CLASS_QUEUE: u8 = 3;
pub const CLASS_BASIC: u8 = 4;
pub const CLASS_TX: u8 = 5;
pub const CLASS_CONFIRM: u8 = 6;
pub const EXCH_DIRECT: u8 = 0;
pub const EXCH_FANOUT: u8 = 1;
pub const EXCH_TOPIC: u8 = 2;
pub const EXCH_HEADERS: u8 = 3;
pub const DMODE_NON_PERSISTENT: u8 = 0;
pub const DMODE_PERSISTENT: u8 = 1;
pub const SEV_CHANNEL_LEVEL: u8 = 0;
pub const SEV_CONNECTION_LEVEL: u8 = 1;
pub const CONN_IDLE: u8 = 0;
pub const CONN_NEGOTIATING: u8 = 1;
pub const CONN_TUNING_OK: u8 = 2;
pub const CONN_OPEN: u8 = 3;
pub const CONN_CLOSING: u8 = 4;
pub const CHAN_CLOSED: u8 = 0;
pub const CHAN_OPENING: u8 = 1;
pub const CHAN_CH_OPEN: u8 = 2;
pub const CHAN_CH_CLOSING: u8 = 3;
pub const BROKER_IDLE: u8 = 0;
pub const BROKER_CONNECTED: u8 = 1;
pub const BROKER_CHANNEL_OPEN: u8 = 2;
pub const BROKER_CONSUMING: u8 = 3;
pub const BROKER_PUBLISHING: u8 = 4;
pub const BROKER_DISCONNECTING: u8 = 5;
