// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-appserver Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const REQ_HTTP: u8 = 0;
pub const REQ_WEBSOCKET: u8 = 1;
pub const REQ_GRPC: u8 = 2;
pub const REQ_GRAPHQL: u8 = 3;
pub const LIFECYCLE_INITIALIZING: u8 = 0;
pub const LIFECYCLE_STARTING: u8 = 1;
pub const LIFECYCLE_RUNNING: u8 = 2;
pub const LIFECYCLE_DRAINING: u8 = 3;
pub const LIFECYCLE_STOPPING: u8 = 4;
pub const LIFECYCLE_STOPPED: u8 = 5;
pub const HEALTH_LIVENESS: u8 = 0;
pub const HEALTH_READINESS: u8 = 1;
pub const HEALTH_STARTUP: u8 = 2;
pub const DEPLOY_ROLLING_UPDATE: u8 = 0;
pub const DEPLOY_BLUE_GREEN: u8 = 1;
pub const DEPLOY_CANARY: u8 = 2;
pub const DEPLOY_RECREATE: u8 = 3;
pub const ERR_CLIENT_ERROR: u8 = 0;
pub const ERR_SERVER_ERROR: u8 = 1;
pub const ERR_TIMEOUT: u8 = 2;
pub const ERR_CIRCUIT_OPEN: u8 = 3;
pub const ERR_RATE_LIMITED: u8 = 4;
