// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: RADIUSABI.{Layout,Transitions,Foreign}. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const PACKET_ACCESS_REQUEST: u8 = 1;
pub const PACKET_ACCESS_ACCEPT: u8 = 2;
pub const PACKET_ACCESS_REJECT: u8 = 3;
pub const PACKET_ACCOUNTING_REQUEST: u8 = 4;
pub const PACKET_ACCOUNTING_RESPONSE: u8 = 5;
pub const PACKET_ACCESS_CHALLENGE: u8 = 11;
pub const ATTR_USER_NAME: u8 = 1;
pub const ATTR_USER_PASSWORD: u8 = 2;
pub const ATTR_NAS_IP_ADDRESS: u8 = 4;
pub const ATTR_NAS_PORT: u8 = 5;
pub const ATTR_SERVICE_TYPE: u8 = 6;
pub const ATTR_FRAMED_PROTOCOL: u8 = 7;
pub const ATTR_FRAMED_IP_ADDRESS: u8 = 8;
pub const ATTR_REPLY_MESSAGE: u8 = 18;
pub const ATTR_SESSION_TIMEOUT: u8 = 27;
pub const SVC_LOGIN: u8 = 1;
pub const SVC_FRAMED: u8 = 2;
pub const SVC_CALLBACK_LOGIN: u8 = 3;
pub const SVC_CALLBACK_FRAMED: u8 = 4;
pub const SVC_OUTBOUND: u8 = 5;
pub const SVC_ADMINISTRATIVE: u8 = 6;
pub const AUTH_PAP: u8 = 0;
pub const AUTH_CHAP: u8 = 1;
pub const AUTH_MSCHAP: u8 = 2;
pub const AUTH_MSCHAPV2: u8 = 3;
pub const AUTH_EAP: u8 = 4;
pub const STATE_IDLE: u8 = 0;
pub const STATE_AUTHENTICATING: u8 = 1;
pub const STATE_AUTHORIZED: u8 = 2;
pub const STATE_REJECTED: u8 = 3;
pub const STATE_CHALLENGED: u8 = 4;
pub const STATE_ACCOUNTING: u8 = 5;
pub const STATE_COMPLETE: u8 = 6;
pub const RESULT_OK: u8 = 0;
pub const RESULT_ERR: u8 = 1;
pub const RESULT_INVALID_PARAM: u8 = 2;
pub const RESULT_POOL_EXHAUSTED: u8 = 3;
pub const RESULT_BAD_SECRET: u8 = 4;
pub const PACKET_HEADER_SIZE: usize = 20;
pub const MAX_PACKET_SIZE: usize = 4096;
pub const ATTRIBUTE_HEADER_SIZE: usize = 2;
pub const MAX_ATTRIBUTE_VALUE_LEN: usize = 253;
