// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-smb Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const COMMAND_NEGOTIATE: u8 = 0;
pub const COMMAND_SESSION_SETUP: u8 = 1;
pub const COMMAND_LOGOFF: u8 = 2;
pub const COMMAND_TREE_CONNECT: u8 = 3;
pub const COMMAND_TREE_DISCONNECT: u8 = 4;
pub const COMMAND_CREATE: u8 = 5;
pub const COMMAND_CLOSE: u8 = 6;
pub const COMMAND_READ: u8 = 7;
pub const COMMAND_WRITE: u8 = 8;
pub const COMMAND_LOCK: u8 = 9;
pub const COMMAND_IOCTL: u8 = 10;
pub const COMMAND_CANCEL: u8 = 11;
pub const COMMAND_QUERY_DIRECTORY: u8 = 12;
pub const COMMAND_CHANGE_NOTIFY: u8 = 13;
pub const COMMAND_QUERY_INFO: u8 = 14;
pub const COMMAND_SET_INFO: u8 = 15;
pub const DIALECT_SMB2_0_2: u8 = 0;
pub const DIALECT_SMB2_1: u8 = 1;
pub const DIALECT_SMB3_0: u8 = 2;
pub const DIALECT_SMB3_0_2: u8 = 3;
pub const DIALECT_SMB3_1_1: u8 = 4;
pub const SHARE_DISK: u8 = 0;
pub const SHARE_PIPE: u8 = 1;
pub const SHARE_PRINT: u8 = 2;
pub const SESSION_IDLE: u8 = 0;
pub const SESSION_NEGOTIATED: u8 = 1;
pub const SESSION_AUTHENTICATED: u8 = 2;
pub const SESSION_TREE_CONNECTED: u8 = 3;
pub const SESSION_FILE_OPEN: u8 = 4;
pub const SESSION_DISCONNECTING: u8 = 5;
