// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-ca Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const CT_ROOT: u8 = 0;
pub const CT_INTERMEDIATE: u8 = 1;
pub const CT_END_ENTITY: u8 = 2;
pub const CT_CROSS_SIGNED: u8 = 3;
pub const CT_CODE_SIGNING: u8 = 4;
pub const CT_EMAIL_PROTECTION: u8 = 5;
pub const CT_OCSP_SIGNING: u8 = 6;
pub const KA_RSA2048: u8 = 0;
pub const KA_RSA4096: u8 = 1;
pub const KA_ECDSA_P256: u8 = 2;
pub const KA_ECDSA_P384: u8 = 3;
pub const KA_ED25519: u8 = 4;
pub const KA_ED448: u8 = 5;
pub const SA_SHA256_WITH_RSA: u8 = 0;
pub const SA_SHA384_WITH_RSA: u8 = 1;
pub const SA_SHA512_WITH_RSA: u8 = 2;
pub const SA_SHA256_WITH_ECDSA: u8 = 3;
pub const SA_SHA384_WITH_ECDSA: u8 = 4;
pub const SA_PURE_ED25519: u8 = 5;
pub const SA_PURE_ED448: u8 = 6;
pub const CS_PENDING: u8 = 0;
pub const CS_ACTIVE: u8 = 1;
pub const CS_REVOKED: u8 = 2;
pub const CS_EXPIRED: u8 = 3;
pub const CS_SUSPENDED: u8 = 4;
pub const RR_UNSPECIFIED: u8 = 0;
pub const RR_KEY_COMPROMISE: u8 = 1;
pub const RR_CA_COMPROMISE: u8 = 2;
pub const RR_AFFILIATION_CHANGED: u8 = 3;
pub const RR_SUPERSEDED: u8 = 4;
pub const RR_CESSATION_OF_OPERATION: u8 = 5;
pub const RR_CERTIFICATE_HOLD: u8 = 6;
pub const CRL_CURRENT: u8 = 0;
pub const CRL_EXPIRED: u8 = 1;
pub const CRL_PENDING: u8 = 2;
pub const CRL_ERROR: u8 = 3;
pub const OCSP_GOOD: u8 = 0;
pub const OCSP_REVOKED: u8 = 1;
pub const OCSP_UNKNOWN: u8 = 2;
pub const OCSP_UNAVAILABLE: u8 = 3;
pub const EXT_BASIC_CONSTRAINTS: u8 = 0;
pub const EXT_KEY_USAGE: u8 = 1;
pub const EXT_EXT_KEY_USAGE: u8 = 2;
pub const EXT_SUBJECT_ALT_NAME: u8 = 3;
pub const EXT_AUTHORITY_INFO_ACCESS: u8 = 4;
pub const EXT_CRL_DISTRIBUTION_POINTS: u8 = 5;
pub const KU_DIGITAL_SIGNATURE: u8 = 0;
pub const KU_NON_REPUDIATION: u8 = 1;
pub const KU_KEY_ENCIPHERMENT: u8 = 2;
pub const KU_DATA_ENCIPHERMENT: u8 = 3;
pub const KU_KEY_AGREEMENT: u8 = 4;
pub const KU_KEY_CERT_SIGN: u8 = 5;
pub const KU_CRL_SIGN: u8 = 6;
pub const KU_ENCIPHER_ONLY: u8 = 7;
pub const KU_DECIPHER_ONLY: u8 = 8;
