// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ProvenGraphql from "../src/ProvenGraphql.res.mjs";

function testOperationTypeRoundtrip() {
  for(var tag = 0; tag <= 2; ++tag){
    var op = ProvenGraphql.operationTypeFromTag(tag);
    if (op !== undefined) {
      if (ProvenGraphql.operationTypeToTag(op) !== tag) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenGraphql_test.res",
                17,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenGraphql_test.res",
              18,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testOperationTypeInvalid() {
  if (ProvenGraphql.operationTypeFromTag(3) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGraphql_test.res",
          22,
          37
        ],
        Error: new Error()
      };
}

function testTypeKindRoundtrip() {
  for(var tag = 0; tag <= 7; ++tag){
    var tk = ProvenGraphql.typeKindFromTag(tag);
    if (tk !== undefined) {
      if (ProvenGraphql.typeKindToTag(tk) !== tag) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenGraphql_test.res",
                32,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenGraphql_test.res",
              33,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testTypeKindInvalid() {
  if (ProvenGraphql.typeKindFromTag(8) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGraphql_test.res",
          37,
          32
        ],
        Error: new Error()
      };
}

function testTypeKindClassification() {
  if (!ProvenGraphql.typeKindIsWrapper(6)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            40,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.typeKindIsWrapper(7)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            41,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGraphql.typeKindIsWrapper(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            42,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.typeKindIsComposite(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            44,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.typeKindIsComposite(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            45,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.typeKindIsComposite(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            46,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGraphql.typeKindIsComposite(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            47,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.typeKindIsComposite(4)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGraphql_test.res",
          48,
          2
        ],
        Error: new Error()
      };
}

function testDirectiveLocationRoundtrip() {
  for(var tag = 0; tag <= 17; ++tag){
    var loc = ProvenGraphql.directiveLocationFromTag(tag);
    if (loc !== undefined) {
      if (ProvenGraphql.directiveLocationToTag(loc) !== tag) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenGraphql_test.res",
                59,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenGraphql_test.res",
              60,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testDirectiveLocationInvalid() {
  if (ProvenGraphql.directiveLocationFromTag(18) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGraphql_test.res",
          64,
          41
        ],
        Error: new Error()
      };
}

function testDirectiveLocationClassification() {
  if (!ProvenGraphql.directiveLocationIsExecutable(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            67,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.directiveLocationIsExecutable(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            68,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.directiveLocationIsExecutable(6)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            69,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGraphql.directiveLocationIsExecutable(7)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            70,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGraphql.directiveLocationIsTypeSystem(7)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGraphql_test.res",
            71,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGraphql.directiveLocationIsTypeSystem(10)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGraphql_test.res",
          72,
          2
        ],
        Error: new Error()
      };
}

function testErrorCategoryRoundtrip() {
  for(var tag = 0; tag <= 4; ++tag){
    var ec = ProvenGraphql.errorCategoryFromTag(tag);
    if (ec !== undefined) {
      if (ProvenGraphql.errorCategoryToTag(ec) !== tag) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenGraphql_test.res",
                83,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenGraphql_test.res",
              84,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testErrorCategoryInvalid() {
  if (ProvenGraphql.errorCategoryFromTag(5) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGraphql_test.res",
          88,
          37
        ],
        Error: new Error()
      };
}

testOperationTypeRoundtrip();

testOperationTypeInvalid();

testTypeKindRoundtrip();

testTypeKindInvalid();

testTypeKindClassification();

testDirectiveLocationRoundtrip();

testDirectiveLocationInvalid();

testDirectiveLocationClassification();

testErrorCategoryRoundtrip();

testErrorCategoryInvalid();

console.log("ProvenGraphql: all tests passed");

export {
  testOperationTypeRoundtrip ,
  testOperationTypeInvalid ,
  testTypeKindRoundtrip ,
  testTypeKindInvalid ,
  testTypeKindClassification ,
  testDirectiveLocationRoundtrip ,
  testDirectiveLocationInvalid ,
  testDirectiveLocationClassification ,
  testErrorCategoryRoundtrip ,
  testErrorCategoryInvalid ,
}
/*  Not a pure module */
