// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ProvenWebsocket from "../src/ProvenWebsocket.res.mjs";

function testOpcodeRoundtrip() {
  var opcodes = [
    [
      0,
      0
    ],
    [
      1,
      1
    ],
    [
      2,
      2
    ],
    [
      8,
      8
    ],
    [
      9,
      9
    ],
    [
      10,
      10
    ]
  ];
  Belt_Array.forEach(opcodes, (function (param) {
          var nibble = param[0];
          var decoded = ProvenWebsocket.opcodeFromNibble(nibble);
          if (!Caml_obj.equal(decoded, param[1])) {
            throw {
                  RE_EXN_ID: "Assert_failure",
                  _1: [
                    "ProvenWebsocket_test.res",
                    16,
                    4
                  ],
                  Error: new Error()
                };
          }
          if (decoded !== undefined) {
            if (ProvenWebsocket.opcodeToNibble(decoded) === nibble) {
              return ;
            }
            throw {
                  RE_EXN_ID: "Assert_failure",
                  _1: [
                    "ProvenWebsocket_test.res",
                    18,
                    18
                  ],
                  Error: new Error()
                };
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenWebsocket_test.res",
                  19,
                  14
                ],
                Error: new Error()
              };
        }));
}

function testOpcodeReservedRejected() {
  var reserved = [
    3,
    4,
    5,
    6,
    7,
    11,
    12,
    13,
    14,
    15
  ];
  Belt_Array.forEach(reserved, (function (nibble) {
          if (ProvenWebsocket.opcodeFromNibble(nibble) === undefined) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenWebsocket_test.res",
                  27,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testOpcodeClassification() {
  if (!ProvenWebsocket.opcodeIsData(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            32,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeIsData(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            33,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeIsData(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            34,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.opcodeIsData(8)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            35,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeIsControl(8)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            37,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeIsControl(9)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            38,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeIsControl(10)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            39,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.opcodeIsControl(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            40,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeIsMessageStart(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            42,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeIsMessageStart(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            43,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.opcodeIsMessageStart(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            44,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeRequiresResponse(9)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            46,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeRequiresResponse(8)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            47,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.opcodeRequiresResponse(1)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenWebsocket_test.res",
          48,
          2
        ],
        Error: new Error()
      };
}

function testCloseCodeRoundtrip() {
  var codes = [
    1000,
    1001,
    1002,
    1003,
    1005,
    1006,
    1007,
    1008,
    1009,
    1010,
    1011
  ];
  Belt_Array.forEach(codes, (function (wire) {
          var code = ProvenWebsocket.closeCodeFromWire(wire);
          if (code !== undefined) {
            if (ProvenWebsocket.closeCodeToWire(code) === wire) {
              return ;
            }
            throw {
                  RE_EXN_ID: "Assert_failure",
                  _1: [
                    "ProvenWebsocket_test.res",
                    60,
                    17
                  ],
                  Error: new Error()
                };
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenWebsocket_test.res",
                  61,
                  14
                ],
                Error: new Error()
              };
        }));
}

function testCloseCodeUnknownRejected() {
  if (ProvenWebsocket.closeCodeFromWire(1004) !== undefined) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            67,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.closeCodeFromWire(999) !== undefined) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            68,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.closeCodeFromWire(1012) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenWebsocket_test.res",
          69,
          2
        ],
        Error: new Error()
      };
}

function testCloseCodeClassification() {
  if (!ProvenWebsocket.closeCodeIsNormal(1000)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            73,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.closeCodeIsNormal(1001)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            74,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.closeCodeIsNormal(1002)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            75,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.closeCodeIsError(1002)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            77,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.closeCodeIsError(1011)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            78,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.closeCodeIsError(1000)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            79,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.closeCodeIsError(1005)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            80,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.closeCodeIsSendable(1000)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            82,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.closeCodeIsSendable(1005)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            83,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.closeCodeIsSendable(1006)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenWebsocket_test.res",
          84,
          2
        ],
        Error: new Error()
      };
}

function testCloseCodeRanges() {
  if (!ProvenWebsocket.isApplicationCode(4000)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            88,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.isApplicationCode(4999)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            89,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.isApplicationCode(3999)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            90,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.isApplicationCode(5000)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            91,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.isPrivateCode(3000)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            93,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.isPrivateCode(3999)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            94,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenWebsocket.isPrivateCode(2999)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            95,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenWebsocket.isPrivateCode(4000)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenWebsocket_test.res",
          96,
          2
        ],
        Error: new Error()
      };
}

function testFrameTextConstruction() {
  var frame = ProvenWebsocket.makeTextFrame([
        104,
        101,
        108,
        108,
        111
      ]);
  if (frame.fin !== true) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            105,
            2
          ],
          Error: new Error()
        };
  }
  if (frame.opcode !== 1) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            106,
            2
          ],
          Error: new Error()
        };
  }
  if (frame.masked) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenWebsocket_test.res",
            107,
            2
          ],
          Error: new Error()
        };
  }
  if (frame.payloadLength === 5) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenWebsocket_test.res",
          108,
          2
        ],
        Error: new Error()
      };
}

function testFrameValidateClientUnmasked() {
  var frame = ProvenWebsocket.makeTextFrame([
        104,
        101,
        108,
        108,
        111
      ]);
  var result = ProvenWebsocket.validateClientFrame(frame, 65536);
  if (Caml_obj.equal(result, "ClientFrameNotMasked")) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenWebsocket_test.res",
          114,
          2
        ],
        Error: new Error()
      };
}

function testFrameValidateServerMasked() {
  var init = ProvenWebsocket.makeTextFrame([
        104,
        101,
        108,
        108,
        111
      ]);
  var frame_fin = init.fin;
  var frame_opcode = init.opcode;
  var frame_payloadLength = init.payloadLength;
  var frame_maskingKey = [
    0,
    0,
    0,
    0
  ];
  var frame_payload = init.payload;
  var frame = {
    fin: frame_fin,
    opcode: frame_opcode,
    masked: true,
    payloadLength: frame_payloadLength,
    maskingKey: frame_maskingKey,
    payload: frame_payload
  };
  var result = ProvenWebsocket.validateServerFrame(frame, 65536);
  if (Caml_obj.equal(result, "ServerFrameMasked")) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenWebsocket_test.res",
          124,
          2
        ],
        Error: new Error()
      };
}

testOpcodeRoundtrip();

testOpcodeReservedRejected();

testOpcodeClassification();

testCloseCodeRoundtrip();

testCloseCodeUnknownRejected();

testCloseCodeClassification();

testCloseCodeRanges();

testFrameTextConstruction();

testFrameValidateClientUnmasked();

testFrameValidateServerMasked();

console.log("ProvenWebsocket: all tests passed");

export {
  testOpcodeRoundtrip ,
  testOpcodeReservedRejected ,
  testOpcodeClassification ,
  testCloseCodeRoundtrip ,
  testCloseCodeUnknownRejected ,
  testCloseCodeClassification ,
  testCloseCodeRanges ,
  testFrameTextConstruction ,
  testFrameValidateClientUnmasked ,
  testFrameValidateServerMasked ,
}
/*  Not a pure module */
