// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ProvenMqtt from "../src/ProvenMqtt.res.mjs";

function testQosRoundtrip() {
  for(var code = 0; code <= 2; ++code){
    var q = ProvenMqtt.qosFromCode(code);
    if (q !== undefined) {
      if (ProvenMqtt.qosToCode(q) !== code) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenMqtt_test.res",
                17,
                19
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenMqtt_test.res",
              18,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testQosReservedRejected() {
  if (ProvenMqtt.qosFromCode(3) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenMqtt_test.res",
          22,
          36
        ],
        Error: new Error()
      };
}

function testQosAckRequirements() {
  if (ProvenMqtt.qosRequiresAck(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            25,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenMqtt.qosRequiresAck(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            26,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenMqtt.qosRequiresAck(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            27,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.qosAckPacketCount(0) !== 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            29,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.qosAckPacketCount(1) !== 1) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            30,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.qosAckPacketCount(2) === 3) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenMqtt_test.res",
          31,
          2
        ],
        Error: new Error()
      };
}

function testQosNegotiation() {
  if (ProvenMqtt.qosEffective(2, 1) !== 1) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            35,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.qosEffective(0, 2) !== 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            36,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.qosDelivery(2, 0) === 0) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenMqtt_test.res",
          37,
          2
        ],
        Error: new Error()
      };
}

function testSubAckCodeRoundtrip() {
  var codes = [
    [
      0,
      0
    ],
    [
      1,
      1
    ],
    [
      2,
      2
    ],
    [
      128,
      128
    ]
  ];
  Belt_Array.forEach(codes, (function (param) {
          var $$byte = param[0];
          var decoded = ProvenMqtt.subAckCodeFromByte($$byte);
          if (!Caml_obj.equal(decoded, param[1])) {
            throw {
                  RE_EXN_ID: "Assert_failure",
                  _1: [
                    "ProvenMqtt_test.res",
                    48,
                    4
                  ],
                  Error: new Error()
                };
          }
          if (decoded !== undefined) {
            if (ProvenMqtt.subAckCodeToByte(decoded) === $$byte) {
              return ;
            }
            throw {
                  RE_EXN_ID: "Assert_failure",
                  _1: [
                    "ProvenMqtt_test.res",
                    50,
                    17
                  ],
                  Error: new Error()
                };
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenMqtt_test.res",
                  51,
                  14
                ],
                Error: new Error()
              };
        }));
}

function testSubAckToQos() {
  if (!Caml_obj.equal(ProvenMqtt.subAckCodeToQos(0), 0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            57,
            2
          ],
          Error: new Error()
        };
  }
  if (!Caml_obj.equal(ProvenMqtt.subAckCodeToQos(1), 1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            58,
            2
          ],
          Error: new Error()
        };
  }
  if (!Caml_obj.equal(ProvenMqtt.subAckCodeToQos(2), 2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            59,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.subAckCodeToQos(128) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenMqtt_test.res",
          60,
          2
        ],
        Error: new Error()
      };
}

function testPacketTypeRoundtrip() {
  for(var code = 1; code <= 15; ++code){
    var pt = ProvenMqtt.packetTypeFromCode(code);
    if (pt !== undefined) {
      if (ProvenMqtt.packetTypeToCode(pt) !== code) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenMqtt_test.res",
                71,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenMqtt_test.res",
              72,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testPacketTypeReservedRejected() {
  if (ProvenMqtt.packetTypeFromCode(0) !== undefined) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            77,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeFromCode(16) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenMqtt_test.res",
          78,
          2
        ],
        Error: new Error()
      };
}

function testPacketTypeDirection() {
  if (ProvenMqtt.packetTypeDirection(1) !== 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            82,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeDirection(2) !== 1) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            83,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeDirection(3) !== 2) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            84,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeDirection(8) !== 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            85,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeDirection(9) === 1) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenMqtt_test.res",
          86,
          2
        ],
        Error: new Error()
      };
}

function testPacketTypePacketId() {
  if (!ProvenMqtt.packetTypeRequiresPacketId(4)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            90,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenMqtt.packetTypeRequiresPacketId(8)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            91,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeRequiresPacketId(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            92,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeRequiresPacketId(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            93,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenMqtt.packetTypeRequiresPacketId(15)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenMqtt_test.res",
            94,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenMqtt.packetTypeRequiresPacketId(14)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenMqtt_test.res",
          95,
          2
        ],
        Error: new Error()
      };
}

testQosRoundtrip();

testQosReservedRejected();

testQosAckRequirements();

testQosNegotiation();

testSubAckCodeRoundtrip();

testSubAckToQos();

testPacketTypeRoundtrip();

testPacketTypeReservedRejected();

testPacketTypeDirection();

testPacketTypePacketId();

console.log("ProvenMqtt: all tests passed");

export {
  testQosRoundtrip ,
  testQosReservedRejected ,
  testQosAckRequirements ,
  testQosNegotiation ,
  testSubAckCodeRoundtrip ,
  testSubAckToQos ,
  testPacketTypeRoundtrip ,
  testPacketTypeReservedRejected ,
  testPacketTypeDirection ,
  testPacketTypePacketId ,
}
/*  Not a pure module */
