// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ProvenHttp from "../src/ProvenHttp.res.mjs";

function testMethodRoundtrip() {
  Belt_Array.forEach(ProvenHttp.allMethods, (function (method) {
          var tag = ProvenHttp.methodToTag(method);
          var decoded = ProvenHttp.methodFromTag(tag);
          if (Caml_obj.equal(decoded, method)) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenHttp_test.res",
                  17,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testMethodParseRoundtrip() {
  Belt_Array.forEach(ProvenHttp.allMethods, (function (method) {
          var s = ProvenHttp.methodAsStr(method);
          var parsed = ProvenHttp.methodParse(s);
          if (Caml_obj.equal(parsed, method)) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenHttp_test.res",
                  24,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testMethodSafety() {
  if (!ProvenHttp.methodIsSafe(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            28,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.methodIsSafe(5)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            29,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenHttp.methodIsSafe(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            30,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.methodIsSafe(3)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenHttp_test.res",
          31,
          2
        ],
        Error: new Error()
      };
}

function testMethodIdempotency() {
  if (!ProvenHttp.methodIsIdempotent(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            35,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.methodIsIdempotent(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            36,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.methodIsIdempotent(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            37,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenHttp.methodIsIdempotent(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            38,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.methodIsIdempotent(4)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenHttp_test.res",
          39,
          2
        ],
        Error: new Error()
      };
}

function testStatusCodeRoundtrip() {
  for(var tag = 0; tag <= 28; ++tag){
    var code = ProvenHttp.statusCodeFromTag(tag);
    if (code !== undefined) {
      if (ProvenHttp.statusCodeToTag(code) !== tag) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenHttp_test.res",
                50,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenHttp_test.res",
              51,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testStatusNumericCode() {
  if (ProvenHttp.statusNumericCode(2) !== 200) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            57,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenHttp.statusNumericCode(14) !== 404) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            58,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenHttp.statusNumericCode(24) === 500) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenHttp_test.res",
          59,
          2
        ],
        Error: new Error()
      };
}

function testStatusFromNumeric() {
  if (!Caml_obj.equal(ProvenHttp.statusFromNumeric(200), 2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            63,
            2
          ],
          Error: new Error()
        };
  }
  if (!Caml_obj.equal(ProvenHttp.statusFromNumeric(404), 14)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            64,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenHttp.statusFromNumeric(999) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenHttp_test.res",
          65,
          2
        ],
        Error: new Error()
      };
}

function testStatusCategoryClassification() {
  if (!ProvenHttp.statusIsSuccess(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            69,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.statusIsError(14)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            70,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.statusIsError(24)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            71,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.statusIsRedirect(6)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            72,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenHttp.statusIsError(2)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenHttp_test.res",
          73,
          2
        ],
        Error: new Error()
      };
}

function testValidHttpTransitions() {
  var validPairs = [
    [
      0,
      1
    ],
    [
      1,
      2
    ],
    [
      2,
      3
    ],
    [
      2,
      4
    ],
    [
      3,
      4
    ],
    [
      4,
      5
    ],
    [
      5,
      6
    ],
    [
      6,
      0
    ],
    [
      1,
      6
    ],
    [
      2,
      6
    ],
    [
      3,
      6
    ],
    [
      4,
      6
    ]
  ];
  Belt_Array.forEach(validPairs, (function (param) {
          if (ProvenHttp.validateHttpTransition(param[0], param[1]) !== undefined) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenHttp_test.res",
                  96,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testInvalidHttpTransitions() {
  var invalidPairs = [
    [
      0,
      4
    ],
    [
      0,
      5
    ],
    [
      4,
      1
    ],
    [
      5,
      2
    ],
    [
      0,
      0
    ]
  ];
  Belt_Array.forEach(invalidPairs, (function (param) {
          if (ProvenHttp.validateHttpTransition(param[0], param[1]) === undefined) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenHttp_test.res",
                  109,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testContentTypeRoundtrip() {
  for(var tag = 0; tag <= 7; ++tag){
    var ct = ProvenHttp.contentTypeFromTag(tag);
    if (ct !== undefined) {
      if (ProvenHttp.contentTypeToTag(ct) !== tag) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenHttp_test.res",
                121,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenHttp_test.res",
              122,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testVersionOrdering() {
  if (ProvenHttp.versionToTag(0) >= ProvenHttp.versionToTag(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            127,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenHttp.versionToTag(1) >= ProvenHttp.versionToTag(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenHttp_test.res",
            128,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenHttp.versionToTag(2) < ProvenHttp.versionToTag(3)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenHttp_test.res",
          129,
          2
        ],
        Error: new Error()
      };
}

testMethodRoundtrip();

testMethodParseRoundtrip();

testMethodSafety();

testMethodIdempotency();

testStatusCodeRoundtrip();

testStatusNumericCode();

testStatusFromNumeric();

testStatusCategoryClassification();

testValidHttpTransitions();

testInvalidHttpTransitions();

testContentTypeRoundtrip();

testVersionOrdering();

console.log("ProvenHttp: all tests passed");

export {
  testMethodRoundtrip ,
  testMethodParseRoundtrip ,
  testMethodSafety ,
  testMethodIdempotency ,
  testStatusCodeRoundtrip ,
  testStatusNumericCode ,
  testStatusFromNumeric ,
  testStatusCategoryClassification ,
  testValidHttpTransitions ,
  testInvalidHttpTransitions ,
  testContentTypeRoundtrip ,
  testVersionOrdering ,
}
/*  Not a pure module */
