// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ProvenGrpc from "../src/ProvenGrpc.res.mjs";

function testStatusCodeRoundtrip() {
  for(var code = 0; code <= 16; ++code){
    var sc = ProvenGrpc.statusCodeFromCode(code);
    if (sc !== undefined) {
      if (ProvenGrpc.statusCodeToCode(sc) !== code) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenGrpc_test.res",
                17,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenGrpc_test.res",
              18,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testStatusCodeInvalid() {
  if (ProvenGrpc.statusCodeFromCode(17) !== undefined) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            23,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.statusCodeFromCode(255) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGrpc_test.res",
          24,
          2
        ],
        Error: new Error()
      };
}

function testStreamTypeClassification() {
  if (ProvenGrpc.streamTypeIsClientStreaming(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            32,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamTypeIsServerStreaming(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            33,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGrpc.streamTypeIsServerStreaming(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            34,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamTypeIsClientStreaming(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            35,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGrpc.streamTypeIsClientStreaming(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            36,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamTypeIsServerStreaming(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            37,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGrpc.streamTypeIsClientStreaming(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            38,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamTypeIsServerStreaming(3)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGrpc_test.res",
          39,
          2
        ],
        Error: new Error()
      };
}

function testStreamStateDataCapabilities() {
  if (!ProvenGrpc.streamCanSendData(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            48,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGrpc.streamCanSendData(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            49,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamCanSendData(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            50,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamCanSendData(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            51,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamCanSendData(5)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            52,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGrpc.streamCanReceiveData(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            55,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGrpc.streamCanReceiveData(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            56,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenGrpc.streamCanReceiveData(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenGrpc_test.res",
            57,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenGrpc.streamCanReceiveData(5)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenGrpc_test.res",
          58,
          2
        ],
        Error: new Error()
      };
}

function testClosedIsTerminal() {
  for(var toTag = 0; toTag <= 5; ++toTag){
    var to_ = ProvenGrpc.streamStateFromTag(toTag);
    if (to_ !== undefined) {
      if (ProvenGrpc.validateStreamTransition(5, to_) !== undefined) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenGrpc_test.res",
                65,
                23
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenGrpc_test.res",
              66,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testValidStreamTransitions() {
  var validPairs = [
    [
      0,
      1
    ],
    [
      1,
      2
    ],
    [
      1,
      3
    ],
    [
      1,
      5
    ],
    [
      2,
      5
    ],
    [
      3,
      5
    ],
    [
      0,
      4
    ],
    [
      4,
      3
    ],
    [
      4,
      5
    ]
  ];
  Belt_Array.forEach(validPairs, (function (param) {
          if (ProvenGrpc.validateStreamTransition(param[0], param[1]) !== undefined) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenGrpc_test.res",
                  83,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testImpossibleStreamTransitions() {
  var impossiblePairs = [
    [
      0,
      2
    ],
    [
      2,
      1
    ],
    [
      4,
      1
    ]
  ];
  Belt_Array.forEach(impossiblePairs, (function (param) {
          if (ProvenGrpc.validateStreamTransition(param[0], param[1]) === undefined) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenGrpc_test.res",
                  94,
                  4
                ],
                Error: new Error()
              };
        }));
}

testStatusCodeRoundtrip();

testStatusCodeInvalid();

testStreamTypeClassification();

testStreamStateDataCapabilities();

testClosedIsTerminal();

testValidStreamTransitions();

testImpossibleStreamTransitions();

console.log("ProvenGrpc: all tests passed");

export {
  testStatusCodeRoundtrip ,
  testStatusCodeInvalid ,
  testStreamTypeClassification ,
  testStreamStateDataCapabilities ,
  testClosedIsTerminal ,
  testValidStreamTransitions ,
  testImpossibleStreamTransitions ,
}
/*  Not a pure module */
