// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as ProvenDns from "../src/ProvenDns.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function testRecordTypeRoundtrip() {
  Belt_Array.forEach(ProvenDns.allRecordTypes, (function (rt) {
          var code = ProvenDns.recordTypeToTypeCode(rt);
          var decoded = ProvenDns.recordTypeFromTypeCode(code);
          if (Caml_obj.equal(decoded, rt)) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenDns_test.res",
                  17,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testRecordTypeUnknownRejected() {
  if (ProvenDns.recordTypeFromTypeCode(0) !== undefined) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            21,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.recordTypeFromTypeCode(255) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          22,
          2
        ],
        Error: new Error()
      };
}

function testRecordTypeClassification() {
  if (!ProvenDns.recordTypeIsAddress(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            26,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenDns.recordTypeIsAddress(28)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            27,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.recordTypeIsAddress(5)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            28,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenDns.recordTypeIsInfrastructure(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            29,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenDns.recordTypeIsInfrastructure(6)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            30,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenDns.recordTypeIsInfrastructure(15)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          31,
          2
        ],
        Error: new Error()
      };
}

function testResponseCodeRoundtrip() {
  for(var code = 0; code <= 5; ++code){
    var rc = ProvenDns.responseCodeFromRcode(code);
    if (rc !== undefined) {
      if (ProvenDns.responseCodeToRcode(rc) !== code) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "ProvenDns_test.res",
                42,
                17
              ],
              Error: new Error()
            };
      }
      
    } else {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ProvenDns_test.res",
              43,
              14
            ],
            Error: new Error()
          };
    }
  }
}

function testResponseCodeInvalid() {
  if (ProvenDns.responseCodeFromRcode(6) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          47,
          36
        ],
        Error: new Error()
      };
}

function testResponseCodeClassification() {
  if (!ProvenDns.responseCodeIsSuccess(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            50,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.responseCodeIsSuccess(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            51,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenDns.responseCodeIsNxdomain(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            52,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenDns.responseCodeIsNxdomain(0)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          53,
          2
        ],
        Error: new Error()
      };
}

function testDomainNameValid() {
  if (!Caml_obj.equal(ProvenDns.validateDomainName("example.com"), {
          TAG: "Ok",
          _0: undefined
        })) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            61,
            2
          ],
          Error: new Error()
        };
  }
  if (!Caml_obj.equal(ProvenDns.validateDomainName("sub.example.com"), {
          TAG: "Ok",
          _0: undefined
        })) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            62,
            2
          ],
          Error: new Error()
        };
  }
  if (Caml_obj.equal(ProvenDns.validateDomainName("a"), {
          TAG: "Ok",
          _0: undefined
        })) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          63,
          2
        ],
        Error: new Error()
      };
}

function testDomainNameEmpty() {
  var match = ProvenDns.validateDomainName("");
  if (match.TAG !== "Ok") {
    var tmp = match._0;
    if (typeof tmp !== "object" && tmp === "EmptyName") {
      return ;
    }
    
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          69,
          9
        ],
        Error: new Error()
      };
}

function testDomainNameEmptyLabel() {
  var match = ProvenDns.validateDomainName("example..com");
  if (match.TAG !== "Ok") {
    var tmp = match._0;
    if (typeof tmp !== "object" && tmp === "EmptyLabel") {
      return ;
    }
    
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          75,
          9
        ],
        Error: new Error()
      };
}

function testDomainNameLabelTooLong() {
  var longLabel = "a".repeat(64);
  var name = longLabel + ".com";
  var match = ProvenDns.validateDomainName(name);
  if (match.TAG !== "Ok") {
    var tmp = match._0;
    if (typeof tmp === "object" && tmp.TAG === "LabelTooLong") {
      return ;
    }
    
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          84,
          9
        ],
        Error: new Error()
      };
}

function testDomainNameTooLong() {
  var label = "a".repeat(63);
  var name = label + "." + label + "." + label + "." + label + ".x";
  if (name.length <= ProvenDns.maxNameLength) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            92,
            2
          ],
          Error: new Error()
        };
  }
  var match = ProvenDns.validateDomainName(name);
  if (match.TAG !== "Ok") {
    var tmp = match._0;
    if (typeof tmp === "object" && tmp.TAG === "NameTooLong") {
      return ;
    }
    
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          95,
          9
        ],
        Error: new Error()
      };
}

function testConstantsMatchIdris() {
  if (ProvenDns.dnsPort !== 53) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            104,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.maxUdpSize !== 512) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            105,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.maxTcpSize !== 65535) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            106,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.maxLabelLength !== 63) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            107,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.maxNameLength !== 253) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenDns_test.res",
            108,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenDns.ednsUdpSize === 4096) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenDns_test.res",
          109,
          2
        ],
        Error: new Error()
      };
}

testRecordTypeRoundtrip();

testRecordTypeUnknownRejected();

testRecordTypeClassification();

testResponseCodeRoundtrip();

testResponseCodeInvalid();

testResponseCodeClassification();

testDomainNameValid();

testDomainNameEmpty();

testDomainNameEmptyLabel();

testDomainNameLabelTooLong();

testDomainNameTooLong();

testConstantsMatchIdris();

console.log("ProvenDns: all tests passed");

export {
  testRecordTypeRoundtrip ,
  testRecordTypeUnknownRejected ,
  testRecordTypeClassification ,
  testResponseCodeRoundtrip ,
  testResponseCodeInvalid ,
  testResponseCodeClassification ,
  testDomainNameValid ,
  testDomainNameEmpty ,
  testDomainNameEmptyLabel ,
  testDomainNameLabelTooLong ,
  testDomainNameTooLong ,
  testConstantsMatchIdris ,
}
/*  Not a pure module */
