// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ProvenCore from "../src/ProvenCore.res.mjs";

function testResultCodeRoundtrip() {
  var codes = [
    0,
    1,
    2,
    3,
    4
  ];
  Belt_Array.forEach(codes, (function (code) {
          var tag = ProvenCore.resultCodeToTag(code);
          var decoded = ProvenCore.resultCodeFromTag(tag);
          if (Caml_obj.equal(decoded, code)) {
            return ;
          }
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "ProvenCore_test.res",
                  17,
                  4
                ],
                Error: new Error()
              };
        }));
}

function testResultCodeInvalidTag() {
  if (ProvenCore.resultCodeFromTag(5) !== undefined) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            22,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.resultCodeFromTag(255) === undefined) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenCore_test.res",
          23,
          2
        ],
        Error: new Error()
      };
}

function testResultCodeClassification() {
  if (!ProvenCore.resultIsOk(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            27,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.resultIsError(0)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            28,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.resultIsOk(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            29,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenCore.resultIsError(1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            30,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenCore.resultIsError(2)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            31,
            2
          ],
          Error: new Error()
        };
  }
  if (!ProvenCore.resultIsError(3)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            32,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.resultIsError(4)) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenCore_test.res",
          33,
          2
        ],
        Error: new Error()
      };
}

function testResultCodeDescription() {
  if (ProvenCore.resultDescription(0) !== "Success") {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            37,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.resultDescription(4) === "Null pointer") {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenCore_test.res",
          38,
          2
        ],
        Error: new Error()
      };
}

function testHandleNonNull() {
  if (ProvenCore.handleNew(0.0) !== undefined) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            46,
            2
          ],
          Error: new Error()
        };
  }
  var h = ProvenCore.handleNew(42.0);
  if (h !== undefined) {
    if (ProvenCore.handleAsPtr(h) === 42.0) {
      return ;
    }
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            49,
            20
          ],
          Error: new Error()
        };
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenCore_test.res",
          50,
          12
        ],
        Error: new Error()
      };
}

function testAlignmentHelpers() {
  if (ProvenCore.paddingFor(0, 8) !== 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            59,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.paddingFor(4, 8) !== 4) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            60,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.paddingFor(8, 8) !== 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            61,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.paddingFor(1, 4) !== 3) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            62,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.alignUp(4, 8) !== 8) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            63,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.alignUp(8, 8) !== 8) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            64,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.alignUp(9, 8) !== 16) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            65,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.alignUp(0, 8) === 0) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenCore_test.res",
          66,
          2
        ],
        Error: new Error()
      };
}

function testPlatformPtrSize() {
  if (ProvenCore.platformPtrSizeBits(0) !== 64) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            74,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.platformPtrSizeBits(1) !== 64) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            75,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.platformPtrSizeBits(2) !== 64) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            76,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.platformPtrSizeBits(3) !== 64) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            77,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.platformPtrSizeBits(4) !== 32) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            78,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.platformPtrSizeBytes(0) !== 8) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ProvenCore_test.res",
            79,
            2
          ],
          Error: new Error()
        };
  }
  if (ProvenCore.platformPtrSizeBytes(4) === 4) {
    return ;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ProvenCore_test.res",
          80,
          2
        ],
        Error: new Error()
      };
}

testResultCodeRoundtrip();

testResultCodeInvalidTag();

testResultCodeClassification();

testResultCodeDescription();

testHandleNonNull();

testAlignmentHelpers();

testPlatformPtrSize();

console.log("ProvenCore: all tests passed");

export {
  testResultCodeRoundtrip ,
  testResultCodeInvalidTag ,
  testResultCodeClassification ,
  testResultCodeDescription ,
  testHandleNonNull ,
  testAlignmentHelpers ,
  testPlatformPtrSize ,
}
/*  Not a pure module */
