// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-chat Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const MSG_TEXT: u8 = 0;
pub const MSG_IMAGE: u8 = 1;
pub const MSG_FILE: u8 = 2;
pub const MSG_SYSTEM: u8 = 3;
pub const MSG_REACTION: u8 = 4;
pub const MSG_EDIT: u8 = 5;
pub const MSG_DELETE: u8 = 6;
pub const MSG_REPLY: u8 = 7;
pub const MSG_THREAD: u8 = 8;
pub const PRESENCE_ONLINE: u8 = 0;
pub const PRESENCE_AWAY: u8 = 1;
pub const PRESENCE_DND: u8 = 2;
pub const PRESENCE_INVISIBLE: u8 = 3;
pub const PRESENCE_OFFLINE: u8 = 4;
pub const ROOM_DIRECT: u8 = 0;
pub const ROOM_GROUP: u8 = 1;
pub const ROOM_CHANNEL: u8 = 2;
pub const ROOM_BROADCAST: u8 = 3;
pub const PERM_READ: u8 = 0;
pub const PERM_WRITE: u8 = 1;
pub const PERM_ADMIN: u8 = 2;
pub const PERM_INVITE: u8 = 3;
pub const PERM_KICK: u8 = 4;
pub const PERM_BAN: u8 = 5;
pub const PERM_PIN: u8 = 6;
pub const PERM_DELETE_OTHERS: u8 = 7;
pub const EVENT_MESSAGE_SENT: u8 = 0;
pub const EVENT_MESSAGE_DELIVERED: u8 = 1;
pub const EVENT_MESSAGE_READ: u8 = 2;
pub const EVENT_USER_JOINED: u8 = 3;
pub const EVENT_USER_LEFT: u8 = 4;
pub const EVENT_TYPING: u8 = 5;
pub const EVENT_ROOM_CREATED: u8 = 6;
