// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: EpistemicABI.{Types,Foreign}. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const TIER_BAND: u8 = 0;
pub const TIER_RELATIONAL: u8 = 1;
pub const TIER_FULL: u8 = 2;
pub const REVEAL_INNOCUOUS: u8 = 0;
pub const REVEAL_CONTEXTUAL: u8 = 1;
pub const REVEAL_SENSITIVE: u8 = 2;
pub const PURPOSE_IDENTIFICATION: u8 = 0;
pub const PURPOSE_ELIGIBILITY: u8 = 1;
pub const PURPOSE_COMPATIBILITY: u8 = 2;
pub const PURPOSE_CONTRACTUAL: u8 = 3;
pub const PURPOSE_AUDIT: u8 = 4;
pub const PHASE_INITIATED: u8 = 0;
pub const PHASE_TIERS_AGREED: u8 = 1;
pub const PHASE_DISCLOSING: u8 = 2;
pub const PHASE_CLOSED: u8 = 3;
pub const ERR_TIER_EXCEEDED: u8 = 0;
pub const ERR_UNKNOWN_FIELD: u8 = 1;
pub const ERR_NO_ACTIVE_SESSION: u8 = 2;
pub const ERR_SESSION_ALREADY_CLOSED: u8 = 3;
pub const ERR_ILL_GOVERNED: u8 = 4;
