// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-backup Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const TYPE_FULL: u8 = 0;
pub const TYPE_INCREMENTAL: u8 = 1;
pub const TYPE_DIFFERENTIAL: u8 = 2;
pub const TYPE_SNAPSHOT: u8 = 3;
pub const TYPE_MIRROR: u8 = 4;
pub const FREQ_HOURLY: u8 = 0;
pub const FREQ_DAILY: u8 = 1;
pub const FREQ_WEEKLY: u8 = 2;
pub const FREQ_MONTHLY: u8 = 3;
pub const FREQ_ON_DEMAND: u8 = 4;
pub const COMP_NONE: u8 = 0;
pub const COMP_GZIP: u8 = 1;
pub const COMP_ZSTD: u8 = 2;
pub const COMP_LZ4: u8 = 3;
pub const COMP_XZ: u8 = 4;
pub const ENC_NO_ENCRYPTION: u8 = 0;
pub const ENC_AES256GCM: u8 = 1;
pub const ENC_CHACHA20POLY1305: u8 = 2;
pub const STATE_IDLE: u8 = 0;
pub const STATE_RUNNING: u8 = 1;
pub const STATE_VERIFYING: u8 = 2;
pub const STATE_COMPLETE: u8 = 3;
pub const STATE_FAILED: u8 = 4;
pub const STATE_CANCELLED: u8 = 5;
pub const RET_KEEP_ALL: u8 = 0;
pub const RET_KEEP_LAST: u8 = 1;
pub const RET_KEEP_DAILY: u8 = 2;
pub const RET_KEEP_WEEKLY: u8 = 3;
pub const RET_KEEP_MONTHLY: u8 = 4;
