// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-ldap Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const SESSION_ANONYMOUS: u8 = 0;
pub const SESSION_BOUND: u8 = 1;
pub const SESSION_CLOSED: u8 = 2;
pub const SESSION_BINDING: u8 = 3;
pub const OP_BIND: u8 = 0;
pub const OP_UNBIND: u8 = 1;
pub const OP_SEARCH: u8 = 2;
pub const OP_MODIFY: u8 = 3;
pub const OP_ADD: u8 = 4;
pub const OP_DELETE: u8 = 5;
pub const OP_MOD_DN: u8 = 6;
pub const OP_COMPARE: u8 = 7;
pub const OP_ABANDON: u8 = 8;
pub const OP_EXTENDED: u8 = 9;
pub const SCOPE_BASE_OBJECT: u8 = 0;
pub const SCOPE_SINGLE_LEVEL: u8 = 1;
pub const SCOPE_WHOLE_SUBTREE: u8 = 2;
pub const RESULT_SUCCESS: u8 = 0;
pub const RESULT_OPERATIONS_ERROR: u8 = 1;
pub const RESULT_PROTOCOL_ERROR: u8 = 2;
pub const RESULT_TIME_LIMIT_EXCEEDED: u8 = 3;
pub const RESULT_SIZE_LIMIT_EXCEEDED: u8 = 4;
pub const RESULT_AUTH_METHOD_NOT_SUPPORTED: u8 = 5;
pub const RESULT_NO_SUCH_OBJECT: u8 = 6;
pub const RESULT_INVALID_CREDENTIALS: u8 = 7;
pub const RESULT_INSUFFICIENT_ACCESS_RIGHTS: u8 = 8;
pub const RESULT_BUSY: u8 = 9;
pub const RESULT_UNAVAILABLE: u8 = 10;
