// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-ocsp Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const CERT_GOOD: u8 = 0;
pub const CERT_REVOKED: u8 = 1;
pub const CERT_UNKNOWN: u8 = 2;
pub const RESPONSE_SUCCESSFUL: u8 = 0;
pub const RESPONSE_MALFORMED_REQUEST: u8 = 1;
pub const RESPONSE_INTERNAL_ERROR: u8 = 2;
pub const RESPONSE_TRY_LATER: u8 = 3;
pub const RESPONSE_SIG_REQUIRED: u8 = 4;
pub const RESPONSE_UNAUTHORIZED: u8 = 5;
pub const HASH_SHA1: u8 = 0;
pub const HASH_SHA256: u8 = 1;
pub const HASH_SHA384: u8 = 2;
pub const HASH_SHA512: u8 = 3;
pub const STATE_IDLE: u8 = 0;
pub const STATE_READY: u8 = 1;
pub const STATE_PROCESSING: u8 = 2;
pub const STATE_SIGNING: u8 = 3;
pub const STATE_CLOSING: u8 = 4;
