; SPDX-License-Identifier: MPL-2.0
; Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>

(library
 (name proven_servers)
 (public_name proven_servers)

 (modules
  proven_servers proven_error proven_unavailable
  proven_agentic proven_airgap proven_amqp proven_apiserver
  proven_appserver proven_authserver proven_backup proven_bfd
  proven_bgp proven_ca proven_cache proven_caldav
  proven_carddav proven_chat proven_coap proven_configmgmt
  proven_container proven_ctlog proven_dbserver proven_dds
  proven_deception proven_dhcp proven_diode proven_dns
  proven_doh proven_doq proven_dot proven_federation
  proven_fileserver proven_firewall proven_ftp proven_gameserver
  proven_git proven_graphdb proven_graphql proven_grpc
  proven_hardened proven_honeypot proven_http proven_httpd
  proven_ids proven_imap proven_irc proven_kerberos
  proven_kms proven_ldap proven_ldp proven_loadbalancer
  proven_logcollector proven_lpd proven_mcp proven_mdns
  proven_media proven_metrics proven_modbus proven_monitor
  proven_mqtt proven_nesy proven_netconf proven_neurosym
  proven_nfs proven_ntp proven_nts proven_objectstore
  proven_ocsp proven_odns proven_opcua proven_ospf
  proven_pop3 proven_pqc proven_proxy proven_ptp
  proven_radius proven_rtsp proven_sandbox proven_sdn
  proven_semweb proven_siem proven_smb proven_smtp
  proven_snmp proven_socks proven_sparql proven_ssh
  proven_ssh_bastion proven_stun proven_syslog proven_tacacs
  proven_telnet proven_tftp proven_tls proven_triplestore
  proven_virt proven_voip proven_vpn proven_wasm
  proven_webdav proven_websocket proven_xmpp proven_zerotrust))
