// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-airgap Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const DIR_IMPORT: u8 = 0;
pub const DIR_EXPORT: u8 = 1;
pub const MEDIA_USB: u8 = 0;
pub const MEDIA_OPTICAL_DISC: u8 = 1;
pub const MEDIA_TAPE_CARTRIDGE: u8 = 2;
pub const MEDIA_DIODE_LINK: u8 = 3;
pub const SCAN_CLEAN: u8 = 0;
pub const SCAN_SUSPICIOUS: u8 = 1;
pub const SCAN_MALICIOUS: u8 = 2;
pub const SCAN_UNSCANNABLE: u8 = 3;
pub const STATE_PENDING: u8 = 0;
pub const STATE_SCANNING: u8 = 1;
pub const STATE_APPROVED: u8 = 2;
pub const STATE_REJECTED: u8 = 3;
pub const STATE_IN_PROGRESS: u8 = 4;
pub const STATE_COMPLETE: u8 = 5;
pub const STATE_FAILED: u8 = 6;
pub const CHECK_HASH_VERIFY: u8 = 0;
pub const CHECK_SIGNATURE_VERIFY: u8 = 1;
pub const CHECK_FORMAT_CHECK: u8 = 2;
pub const CHECK_CONTENT_INSPECTION: u8 = 3;
pub const CHECK_MALWARE_SCAN: u8 = 4;
