// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-telnet Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const CMD_SE: u8 = 0;
pub const CMD_NOP: u8 = 1;
pub const CMD_DATA_MARK: u8 = 2;
pub const CMD_BRK: u8 = 3;
pub const CMD_INTERRUPT_PROCESS: u8 = 4;
pub const CMD_ABORT_OUTPUT: u8 = 5;
pub const CMD_ARE_YOU_THERE: u8 = 6;
pub const CMD_ERASE_CHAR: u8 = 7;
pub const CMD_ERASE_LINE: u8 = 8;
pub const CMD_GO_AHEAD: u8 = 9;
pub const CMD_SB: u8 = 10;
pub const CMD_WILL: u8 = 11;
pub const CMD_WONT: u8 = 12;
pub const CMD_DO_: u8 = 13;
pub const CMD_DONT: u8 = 14;
pub const CMD_IAC: u8 = 15;
pub const OPT_ECHO: u8 = 0;
pub const OPT_SUPPRESS_GO_AHEAD: u8 = 1;
pub const OPT_STATUS: u8 = 2;
pub const OPT_TIMING_MARK: u8 = 3;
pub const OPT_TERMINAL_TYPE: u8 = 4;
pub const OPT_WINDOW_SIZE: u8 = 5;
pub const OPT_TERMINAL_SPEED: u8 = 6;
pub const OPT_REMOTE_FLOW_CONTROL: u8 = 7;
pub const OPT_LINEMODE: u8 = 8;
pub const OPT_ENVIRONMENT: u8 = 9;
pub const NEG_INACTIVE: u8 = 0;
pub const NEG_WILL_SENT: u8 = 1;
pub const NEG_DO_SENT: u8 = 2;
pub const NEG_ACTIVE: u8 = 3;
pub const SESSION_IDLE: u8 = 0;
pub const SESSION_NEGOTIATING: u8 = 1;
pub const SESSION_ACTIVE: u8 = 2;
pub const SESSION_SUBNEG: u8 = 3;
pub const SESSION_CLOSING: u8 = 4;
