#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
#
# gen-abi.sh -- regenerate a protocol's C header + Zig constants for its ABI
# tags FROM the proven Idris encoders (single source of truth).
#
# The Idris emitter (e.g. EpistemicABI.Emit) prints a neutral manifest derived
# from the proven `*ToTag` functions; this script renders that manifest into
# both targets. DETERMINISTIC: no timestamps, fixed order, LC_ALL=C -- so CI can
# regenerate and assert `git diff --exit-code` to prove the artifacts still
# match the proofs.
#
# Milestone 1 wires the epistemic pilot; the rendering half generalizes
# unchanged across protocols (Milestone 2 loops the per-protocol config below).

set -euo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ---- per-protocol config (Milestone 2: loop this) --------------------------
PROTO_DIR="protocols/proven-epistemic"
ABIGEN_IPKG="proven-epistemic-abigen.ipkg"   # relative to PROTO_DIR
ABIGEN_EXEC="build/exec/epistemic-abigen"     # relative to PROTO_DIR
PREFIX="EPISTEMIC"                            # C macro / Zig const prefix
GUARD="PROVEN_EPISTEMIC_H"
H_OUT="$PROTO_DIR/generated/abi/epistemic.h"
ZIG_OUT="$PROTO_DIR/ffi/zig/src/epistemic_abi_gen.zig"

SPDX="SPDX-License-Identifier: MPL-2.0"
COPY="Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>"

# ---- build + run the Idris emitter (manifest only on stdout) ---------------
( cd "$PROTO_DIR" && idris2 --build "$ABIGEN_IPKG" ) >/dev/null 2>&1 \
  || { echo "gen-abi: idris2 build failed for $PROTO_DIR/$ABIGEN_IPKG" >&2; exit 1; }
MANIFEST="$( cd "$PROTO_DIR" && "./$ABIGEN_EXEC" )"

mkdir -p "$(dirname "$H_OUT")" "$(dirname "$ZIG_OUT")"

# ---- render C header -------------------------------------------------------
{
  echo "// $SPDX"
  echo "// $COPY"
  echo "/*"
  echo " * $(basename "$H_OUT") -- C-ABI tag header for $(basename "$PROTO_DIR")."
  echo " * @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT."
  echo " * Single source of truth: EpistemicABI.{Types,Foreign}. Regenerate: bash tools/gen-abi.sh"
  echo " */"
  echo "#ifndef $GUARD"
  echo "#define $GUARD"
  echo ""
  echo "#include <stdint.h>"
  echo ""
  echo "#ifdef __cplusplus"
  echo 'extern "C" {'
  echo "#endif"
  echo ""
  awk -v p="$PREFIX" '
    $1=="ABI_VERSION" { printf "#define %s_ABI_VERSION %s\n\n", p, $2; next }
    { printf "#define %s_%s_%s %s\n", p, $1, $2, $3 }
  ' <<< "$MANIFEST"
  echo ""
  echo "/* FFI contract (mirrors ffi/zig/src/epistemic.zig exports). */"
  echo "uint32_t epistemic_abi_version(void);"
  echo "uint8_t  epistemic_meet(uint8_t a, uint8_t b);"
  echo "uint8_t  epistemic_well_governed(uint8_t revealingness, uint8_t min_tier);"
  echo "int      epistemic_create(void);"
  echo "void     epistemic_destroy(int slot);"
  echo "uint8_t  epistemic_phase(int slot);"
  echo "uint8_t  epistemic_effective_tier(int slot);"
  echo "uint8_t  epistemic_can_transition(uint8_t from, uint8_t to);"
  echo "uint8_t  epistemic_agree_tiers(int slot, uint8_t granted, uint8_t theirs);"
  echo "uint8_t  epistemic_begin_disclosure(int slot);"
  echo "uint8_t  epistemic_close(int slot);"
  echo "uint8_t  epistemic_disclose(int slot, uint8_t min_tier, uint8_t revealingness);"
  echo ""
  echo "#ifdef __cplusplus"
  echo "}"
  echo "#endif"
  echo ""
  echo "#endif /* $GUARD */"
} > "$H_OUT"

# ---- render Zig constants --------------------------------------------------
{
  echo "// $SPDX"
  echo "// $COPY"
  echo "//"
  echo "// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT."
  echo "// Single source of truth: EpistemicABI.{Types,Foreign}. Regenerate: bash tools/gen-abi.sh"
  echo ""
  awk '
    $1=="ABI_VERSION" { printf "pub const ABI_VERSION: u32 = %s;\n\n", $2; next }
    { printf "pub const %s_%s: u8 = %s;\n", $1, $2, $3 }
  ' <<< "$MANIFEST"
} > "$ZIG_OUT"

echo "gen-abi: wrote $H_OUT and $ZIG_OUT" >&2
