#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
#
# gen-abi.sh -- regenerate each conformance-enabled protocol's C header + Zig
# constants for its ABI tags FROM the proven Idris encoders (single source of
# truth).
#
# The Idris emitter (<Name>ABI.Emit) prints a neutral manifest derived from the
# proven `*ToTag` functions; this script renders that manifest into both
# targets. DETERMINISTIC: no timestamps, fixed order, LC_ALL=C -- so CI can
# regenerate and assert `git diff --exit-code` to prove the artifacts still
# match the proofs.
#
# One shared renderer (gen_protocol) + one tiny per-protocol emitter each. To
# onboard a protocol: add its <Name>ABI.Emit + <name>-abigen.ipkg, a protos_*
# function, and a gen_protocol call at the bottom.

set -euo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SPDX="SPDX-License-Identifier: MPL-2.0"
COPY="Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>"

# gen_protocol <proto_dir> <abigen_ipkg> <abigen_exec> <prefix> <guard> \
#              <sot> <h_out> <zig_out> <protos_fn>
gen_protocol() {
  local PROTO_DIR="$1" IPKG="$2" EXEC="$3" PREFIX="$4" GUARD="$5" SOT="$6" \
        H_OUT="$7" ZIG_OUT="$8" PROTOS_FN="$9"

  ( cd "$PROTO_DIR" && idris2 --build "$IPKG" ) >/dev/null 2>&1 \
    || { echo "gen-abi: idris2 build failed for $PROTO_DIR/$IPKG" >&2; exit 1; }
  local MANIFEST; MANIFEST="$( cd "$PROTO_DIR" && "./$EXEC" )"

  mkdir -p "$(dirname "$H_OUT")" "$(dirname "$ZIG_OUT")"

  # ---- C header -----------------------------------------------------------
  {
    echo "// $SPDX"
    echo "// $COPY"
    echo "/*"
    echo " * $(basename "$H_OUT") -- C-ABI tag header for $(basename "$PROTO_DIR")."
    echo " * @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT."
    echo " * Single source of truth: $SOT. Regenerate: bash tools/gen-abi.sh"
    echo " */"
    echo "#ifndef $GUARD"
    echo "#define $GUARD"
    echo ""
    echo "#include <stdint.h>"
    echo ""
    echo "#ifdef __cplusplus"
    echo 'extern "C" {'
    echo "#endif"
    echo ""
    awk -v p="$PREFIX" '
      $1=="ABI_VERSION" { printf "#define %s_ABI_VERSION %s\n\n", p, $2; next }
      $1=="LAYOUT"      { printf "#define %s_%s %s\n", p, $2, $3; next }
      { printf "#define %s_%s_%s %s\n", p, $1, $2, $3 }
    ' <<< "$MANIFEST"
    echo ""
    "$PROTOS_FN"
    echo ""
    echo "#ifdef __cplusplus"
    echo "}"
    echo "#endif"
    echo ""
    echo "#endif /* $GUARD */"
  } > "$H_OUT"

  # ---- Zig constants ------------------------------------------------------
  {
    echo "// $SPDX"
    echo "// $COPY"
    echo "//"
    echo "// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT."
    echo "// Single source of truth: $SOT. Regenerate: bash tools/gen-abi.sh"
    echo ""
    awk '
      $1=="ABI_VERSION" { printf "pub const ABI_VERSION: u32 = %s;\n\n", $2; next }
      $1=="LAYOUT"      { printf "pub const %s: usize = %s;\n", $2, $3; next }
      { printf "pub const %s_%s: u8 = %s;\n", $1, $2, $3 }
    ' <<< "$MANIFEST"
  } > "$ZIG_OUT"

  echo "gen-abi: wrote $H_OUT and $ZIG_OUT" >&2
}

# --- per-protocol FFI prototype blocks (mirror the Zig exports) -------------
protos_epistemic() {
  echo "/* FFI contract (mirrors ffi/zig/src/epistemic.zig exports). */"
  echo "uint32_t epistemic_abi_version(void);"
  echo "uint8_t  epistemic_meet(uint8_t a, uint8_t b);"
  echo "uint8_t  epistemic_well_governed(uint8_t revealingness, uint8_t min_tier);"
  echo "int      epistemic_create(void);"
  echo "void     epistemic_destroy(int slot);"
  echo "uint8_t  epistemic_phase(int slot);"
  echo "uint8_t  epistemic_effective_tier(int slot);"
  echo "uint8_t  epistemic_can_transition(uint8_t from, uint8_t to);"
  echo "uint8_t  epistemic_agree_tiers(int slot, uint8_t granted, uint8_t theirs);"
  echo "uint8_t  epistemic_begin_disclosure(int slot);"
  echo "uint8_t  epistemic_close(int slot);"
  echo "uint8_t  epistemic_disclose(int slot, uint8_t min_tier, uint8_t revealingness);"
}

protos_radius() {
  echo "/* FFI contract (mirrors ffi/zig/src/radius.zig exports). */"
  echo "uint32_t radius_abi_version(void);"
  echo "int      radius_session_create(uint8_t auth_method);"
  echo "void     radius_session_destroy(int slot);"
  echo "uint8_t  radius_session_state(int slot);"
  echo "uint8_t  radius_get_auth_method(int slot);"
  echo "uint8_t  radius_get_packet_id(int slot);"
  echo "uint8_t  radius_get_attribute_count(int slot);"
  echo "uint8_t  radius_begin_auth(int slot, uint8_t pkt_id);"
  echo "uint8_t  radius_accept_auth(int slot);"
  echo "uint8_t  radius_reject_auth(int slot);"
  echo "uint8_t  radius_challenge_auth(int slot);"
  echo "uint8_t  radius_respond_challenge(int slot);"
  echo "uint8_t  radius_begin_accounting(int slot);"
  echo "uint8_t  radius_end_accounting(int slot);"
  echo "uint8_t  radius_end_session(int slot);"
  echo "uint8_t  radius_can_transition(uint8_t from, uint8_t to);"
  echo "uint8_t  radius_set_secret(int slot, const uint8_t *secret_ptr, uint32_t secret_len);"
  echo "uint8_t  radius_add_attribute(int slot, uint8_t attr_type, const uint8_t *value_ptr, uint8_t value_len);"
}

# --- conformance-enabled protocols -----------------------------------------
gen_protocol "protocols/proven-epistemic" "proven-epistemic-abigen.ipkg" \
  "build/exec/epistemic-abigen" "EPISTEMIC" "PROVEN_EPISTEMIC_H" \
  "EpistemicABI.{Types,Foreign}" \
  "protocols/proven-epistemic/generated/abi/epistemic.h" \
  "protocols/proven-epistemic/ffi/zig/src/epistemic_abi_gen.zig" \
  protos_epistemic

gen_protocol "protocols/proven-radius" "proven-radius-abigen.ipkg" \
  "build/exec/radius-abigen" "RADIUS" "PROVEN_RADIUS_H" \
  "RADIUSABI.{Layout,Transitions,Foreign}" \
  "protocols/proven-radius/generated/abi/radius.h" \
  "protocols/proven-radius/ffi/zig/src/radius_abi_gen.zig" \
  protos_radius
