#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
#
# gen-abi.sh -- regenerate each conformance-enabled protocol's ABI artifacts
# FROM the proven Idris encoders (single source of truth).
#
#   bash tools/gen-abi.sh            # regenerate every conformance protocol
#   bash tools/gen-abi.sh <name>     # regenerate just one (used per-protocol)
#
# Each <Name>ABI.Emit prints a neutral manifest derived from the proven `*ToTag`
# functions; this script renders it into a Zig constants file consumed by a
# comptime guard in the engine (and, for the two reference protocols, a C header
# too). DETERMINISTIC: no timestamps, fixed order, LC_ALL=C -- so CI can
# regenerate and `git diff --exit-code` to prove the artifacts match the proofs.
#
# Onboarding a protocol touches ONLY per-protocol files (add <Name>ABI.Emit +
# proven-<name>-abigen.ipkg + the comptime guard); this script auto-discovers it
# via the abigen ipkg glob.

set -euo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SPDX="SPDX-License-Identifier: MPL-2.0"
COPY="Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>"

# Render the Zig constants from a neutral manifest on stdin-substitution.
render_zig() {  # <manifest> <zig_out> <sot>
  local MANIFEST="$1" ZIG_OUT="$2" SOT="$3"
  mkdir -p "$(dirname "$ZIG_OUT")"
  {
    echo "// $SPDX"
    echo "// $COPY"
    echo "//"
    echo "// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT."
    echo "// Single source of truth: $SOT. Regenerate: bash tools/gen-abi.sh"
    echo ""
    awk '
      $1=="ABI_VERSION" { printf "pub const ABI_VERSION: u32 = %s;\n\n", $2; next }
      $1=="LAYOUT"      { printf "pub const %s: usize = %s;\n", $2, $3; next }
      { printf "pub const %s_%s: u8 = %s;\n", $1, $2, $3 }
    ' <<< "$MANIFEST"
  } > "$ZIG_OUT"
}

# Build the emitter and capture its manifest.
build_manifest() {  # <proto_dir> <ipkg> <exec>  -> echoes manifest
  local PROTO_DIR="$1" IPKG="$2" EXEC="$3"
  ( cd "$PROTO_DIR" && idris2 --build "$IPKG" ) >/dev/null 2>&1 \
    || { echo "gen-abi: idris2 build failed for $PROTO_DIR/$IPKG" >&2; return 1; }
  ( cd "$PROTO_DIR" && "./$EXEC" )
}

# Full treatment (C header WITH FFI prototypes + Zig constants) -- reference protocols.
gen_protocol() {  # <proto_dir> <ipkg> <exec> <prefix> <guard> <sot> <h_out> <zig_out> <protos_fn>
  local PROTO_DIR="$1" IPKG="$2" EXEC="$3" PREFIX="$4" GUARD="$5" SOT="$6" \
        H_OUT="$7" ZIG_OUT="$8" PROTOS_FN="$9"
  local MANIFEST; MANIFEST="$(build_manifest "$PROTO_DIR" "$IPKG" "$EXEC")" || return 1
  mkdir -p "$(dirname "$H_OUT")" "$(dirname "$ZIG_OUT")"
  {
    echo "// $SPDX"
    echo "// $COPY"
    echo "/*"
    echo " * $(basename "$H_OUT") -- C-ABI tag header for $(basename "$PROTO_DIR")."
    echo " * @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT."
    echo " * Single source of truth: $SOT. Regenerate: bash tools/gen-abi.sh"
    echo " */"
    echo "#ifndef $GUARD"
    echo "#define $GUARD"
    echo ""
    echo "#include <stdint.h>"
    echo ""
    echo "#ifdef __cplusplus"
    echo 'extern "C" {'
    echo "#endif"
    echo ""
    awk -v p="$PREFIX" '
      $1=="ABI_VERSION" { printf "#define %s_ABI_VERSION %s\n\n", p, $2; next }
      $1=="LAYOUT"      { printf "#define %s_%s %s\n", p, $2, $3; next }
      { printf "#define %s_%s_%s %s\n", p, $1, $2, $3 }
    ' <<< "$MANIFEST"
    echo ""
    "$PROTOS_FN"
    echo ""
    echo "#ifdef __cplusplus"
    echo "}"
    echo "#endif"
    echo ""
    echo "#endif /* $GUARD */"
  } > "$H_OUT"
  render_zig "$MANIFEST" "$ZIG_OUT" "$SOT"
  echo "gen-abi: wrote $H_OUT and $ZIG_OUT" >&2
}

# Zig-constants-only treatment -- swept protocols (the comptime guard is the
# conformance mechanism; the C header for these stays as-is for now).
gen_zig_only() {  # <name>
  local name="$1"
  local PROTO_DIR="protocols/proven-$name"
  local ZIG_OUT="$PROTO_DIR/ffi/zig/src/${name}_abi_gen.zig"
  local MANIFEST
  MANIFEST="$(build_manifest "$PROTO_DIR" "proven-$name-abigen.ipkg" "build/exec/$name-abigen")" || return 1
  render_zig "$MANIFEST" "$ZIG_OUT" "the proven proven-$name Idris ABI encoders"
  echo "gen-abi: wrote $ZIG_OUT" >&2
}

# --- per-protocol FFI prototype blocks (reference protocols) ----------------
protos_epistemic() {
  echo "/* FFI contract (mirrors ffi/zig/src/epistemic.zig exports). */"
  echo "uint32_t epistemic_abi_version(void);"
  echo "uint8_t  epistemic_meet(uint8_t a, uint8_t b);"
  echo "uint8_t  epistemic_well_governed(uint8_t revealingness, uint8_t min_tier);"
  echo "int      epistemic_create(void);"
  echo "void     epistemic_destroy(int slot);"
  echo "uint8_t  epistemic_phase(int slot);"
  echo "uint8_t  epistemic_effective_tier(int slot);"
  echo "uint8_t  epistemic_can_transition(uint8_t from, uint8_t to);"
  echo "uint8_t  epistemic_agree_tiers(int slot, uint8_t granted, uint8_t theirs);"
  echo "uint8_t  epistemic_begin_disclosure(int slot);"
  echo "uint8_t  epistemic_close(int slot);"
  echo "uint8_t  epistemic_disclose(int slot, uint8_t min_tier, uint8_t revealingness);"
}

protos_radius() {
  echo "/* FFI contract (mirrors ffi/zig/src/radius.zig exports). */"
  echo "uint32_t radius_abi_version(void);"
  echo "int      radius_session_create(uint8_t auth_method);"
  echo "void     radius_session_destroy(int slot);"
  echo "uint8_t  radius_session_state(int slot);"
  echo "uint8_t  radius_get_auth_method(int slot);"
  echo "uint8_t  radius_get_packet_id(int slot);"
  echo "uint8_t  radius_get_attribute_count(int slot);"
  echo "uint8_t  radius_begin_auth(int slot, uint8_t pkt_id);"
  echo "uint8_t  radius_accept_auth(int slot);"
  echo "uint8_t  radius_reject_auth(int slot);"
  echo "uint8_t  radius_challenge_auth(int slot);"
  echo "uint8_t  radius_respond_challenge(int slot);"
  echo "uint8_t  radius_begin_accounting(int slot);"
  echo "uint8_t  radius_end_accounting(int slot);"
  echo "uint8_t  radius_end_session(int slot);"
  echo "uint8_t  radius_can_transition(uint8_t from, uint8_t to);"
  echo "uint8_t  radius_set_secret(int slot, const uint8_t *secret_ptr, uint32_t secret_len);"
  echo "uint8_t  radius_add_attribute(int slot, uint8_t attr_type, const uint8_t *value_ptr, uint8_t value_len);"
}

gen_epistemic() {
  gen_protocol "protocols/proven-epistemic" "proven-epistemic-abigen.ipkg" \
    "build/exec/epistemic-abigen" "EPISTEMIC" "PROVEN_EPISTEMIC_H" \
    "EpistemicABI.{Types,Foreign}" \
    "protocols/proven-epistemic/generated/abi/epistemic.h" \
    "protocols/proven-epistemic/ffi/zig/src/epistemic_abi_gen.zig" \
    protos_epistemic
}

gen_radius() {
  gen_protocol "protocols/proven-radius" "proven-radius-abigen.ipkg" \
    "build/exec/radius-abigen" "RADIUS" "PROVEN_RADIUS_H" \
    "RADIUSABI.{Layout,Transitions,Foreign}" \
    "protocols/proven-radius/generated/abi/radius.h" \
    "protocols/proven-radius/ffi/zig/src/radius_abi_gen.zig" \
    protos_radius
}

# --- entry point -----------------------------------------------------------
if [ "${1:-}" != "" ]; then
  case "$1" in
    epistemic) gen_epistemic ;;
    radius)    gen_radius ;;
    *)         gen_zig_only "$1" ;;
  esac
  exit 0
fi

# All conformance protocols: the two reference ones (full), then every other
# protocol that ships an abigen ipkg (Zig constants only).
gen_epistemic
gen_radius
for ipkg in protocols/*/proven-*-abigen.ipkg; do
  [ -f "$ipkg" ] || continue
  name="$(basename "$ipkg" | sed -e 's/^proven-//' -e 's/-abigen\.ipkg$//')"
  case "$name" in epistemic|radius) continue ;; esac
  gen_zig_only "$name"
done
