// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-cache Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const CMD_GET: u8 = 0;
pub const CMD_SET: u8 = 1;
pub const CMD_DELETE: u8 = 2;
pub const CMD_EXISTS: u8 = 3;
pub const CMD_EXPIRE: u8 = 4;
pub const CMD_TTL: u8 = 5;
pub const CMD_KEYS: u8 = 6;
pub const CMD_FLUSH: u8 = 7;
pub const CMD_INCR: u8 = 8;
pub const CMD_DECR: u8 = 9;
pub const CMD_APPEND: u8 = 10;
pub const CMD_PREPEND: u8 = 11;
pub const CMD_CAS: u8 = 12;
pub const EVICT_LRU: u8 = 0;
pub const EVICT_LFU: u8 = 1;
pub const EVICT_RANDOM: u8 = 2;
pub const EVICT_EVICT_TTL: u8 = 3;
pub const EVICT_NO_EVICTION: u8 = 4;
pub const DTYPE_STRING_VAL: u8 = 0;
pub const DTYPE_INT_VAL: u8 = 1;
pub const DTYPE_LIST_VAL: u8 = 2;
pub const DTYPE_SET_VAL: u8 = 3;
pub const DTYPE_HASH_VAL: u8 = 4;
pub const ERR_NOT_FOUND: u8 = 0;
pub const ERR_TYPE_MISMATCH: u8 = 1;
pub const ERR_OUT_OF_MEMORY: u8 = 2;
pub const ERR_KEY_TOO_LONG: u8 = 3;
pub const ERR_VALUE_TOO_LARGE: u8 = 4;
pub const ERR_CAS_CONFLICT: u8 = 5;
pub const REPL_NONE: u8 = 0;
pub const REPL_PRIMARY: u8 = 1;
pub const REPL_REPLICA: u8 = 2;
pub const REPL_SENTINEL: u8 = 3;
