// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-configmgmt Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const RT_FILE: u8 = 0;
pub const RT_PACKAGE: u8 = 1;
pub const RT_SERVICE: u8 = 2;
pub const RT_USER: u8 = 3;
pub const RT_GROUP: u8 = 4;
pub const RT_CRON: u8 = 5;
pub const RT_MOUNT: u8 = 6;
pub const RT_FIREWALL: u8 = 7;
pub const RT_REGISTRY: u8 = 8;
pub const RS_PRESENT: u8 = 0;
pub const RS_ABSENT: u8 = 1;
pub const RS_RUNNING: u8 = 2;
pub const RS_STOPPED: u8 = 3;
pub const RS_ENABLED: u8 = 4;
pub const RS_DISABLED: u8 = 5;
pub const ACT_CREATE: u8 = 0;
pub const ACT_MODIFY: u8 = 1;
pub const ACT_DELETE: u8 = 2;
pub const ACT_RESTART: u8 = 3;
pub const ACT_RELOAD: u8 = 4;
pub const ACT_SKIP: u8 = 5;
pub const DS_IN_SYNC: u8 = 0;
pub const DS_DRIFTED: u8 = 1;
pub const DS_UNKNOWN: u8 = 2;
pub const DS_UNMANAGED: u8 = 3;
pub const AM_ENFORCE: u8 = 0;
pub const AM_DRY_RUN: u8 = 1;
pub const AM_AUDIT: u8 = 2;
