// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-apiserver Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const AUTH_API_KEY: u8 = 0;
pub const AUTH_BEARER: u8 = 1;
pub const AUTH_BASIC: u8 = 2;
pub const AUTH_OAUTH2: u8 = 3;
pub const AUTH_HMAC: u8 = 4;
pub const AUTH_MTLS: u8 = 5;
pub const RATE_FIXED_WINDOW: u8 = 0;
pub const RATE_SLIDING_WINDOW: u8 = 1;
pub const RATE_TOKEN_BUCKET: u8 = 2;
pub const RATE_LEAKY_BUCKET: u8 = 3;
pub const VER_V1: u8 = 0;
pub const VER_V2: u8 = 1;
pub const VER_V3: u8 = 2;
pub const VER_LATEST: u8 = 3;
pub const VER_DEPRECATED: u8 = 4;
pub const FMT_JSON: u8 = 0;
pub const FMT_XML: u8 = 1;
pub const FMT_PROTOBUF: u8 = 2;
pub const FMT_MESSAGEPACK: u8 = 3;
pub const ERR_UNAUTHORIZED: u8 = 0;
pub const ERR_RATE_LIMITED: u8 = 1;
pub const ERR_NOT_FOUND: u8 = 2;
pub const ERR_BAD_REQUEST: u8 = 3;
pub const ERR_SERVICE_UNAVAILABLE: u8 = 4;
pub const ERR_CIRCUIT_OPEN: u8 = 5;
