// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-ctlog Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const ENTRY_X509_ENTRY: u8 = 0;
pub const ENTRY_PRECERT_ENTRY: u8 = 1;
pub const SIG_CERTIFICATE_TIMESTAMP: u8 = 0;
pub const SIG_TREE_HASH: u8 = 1;
pub const LEAF_TIMESTAMPED_ENTRY: u8 = 0;
pub const SUBMIT_ACCEPTED: u8 = 0;
pub const SUBMIT_DUPLICATE: u8 = 1;
pub const SUBMIT_RATE_LIMITED: u8 = 2;
pub const SUBMIT_REJECTED: u8 = 3;
pub const SUBMIT_INVALID_CHAIN: u8 = 4;
pub const SUBMIT_UNKNOWN_ANCHOR: u8 = 5;
pub const VERIFY_VALID_PROOF: u8 = 0;
pub const VERIFY_INVALID_PROOF: u8 = 1;
pub const VERIFY_INCONSISTENT_TREE: u8 = 2;
pub const VERIFY_STALE_STH: u8 = 3;
pub const STATE_IDLE: u8 = 0;
pub const STATE_ACTIVE: u8 = 1;
pub const STATE_MERGING: u8 = 2;
pub const STATE_SIGNING: u8 = 3;
pub const STATE_SHUTDOWN: u8 = 4;
