// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by tools/gen-abi.sh from the proven Idris ABI encoders -- DO NOT EDIT.
// Single source of truth: the proven proven-coap Idris ABI encoders. Regenerate: bash tools/gen-abi.sh

pub const ABI_VERSION: u32 = 1;

pub const METHOD_GET: u8 = 0;
pub const METHOD_POST: u8 = 1;
pub const METHOD_PUT: u8 = 2;
pub const METHOD_DELETE: u8 = 3;
pub const MSGTYPE_CONFIRMABLE: u8 = 0;
pub const MSGTYPE_NON_CONFIRMABLE: u8 = 1;
pub const MSGTYPE_ACKNOWLEDGEMENT: u8 = 2;
pub const MSGTYPE_RESET: u8 = 3;
pub const FORMAT_TEXT_PLAIN: u8 = 0;
pub const FORMAT_LINK_FORMAT: u8 = 1;
pub const FORMAT_XML: u8 = 2;
pub const FORMAT_OCTET_STREAM: u8 = 3;
pub const FORMAT_EXI: u8 = 4;
pub const FORMAT_JSON: u8 = 5;
pub const FORMAT_CBOR: u8 = 6;
pub const RESPCLASS_SUCCESS: u8 = 0;
pub const RESPCLASS_CLIENT_ERROR: u8 = 1;
pub const RESPCLASS_SERVER_ERROR: u8 = 2;
pub const RESPCLASS_SIGNALING: u8 = 3;
pub const RESPCLASS_EMPTY: u8 = 4;
pub const STATE_IDLE: u8 = 0;
pub const STATE_BOUND: u8 = 1;
pub const STATE_SERVING: u8 = 2;
pub const STATE_OBSERVING: u8 = 3;
pub const STATE_SHUTDOWN: u8 = 4;
