// Generated by ReScript, PLEASE EDIT WITH CARE


function statusCodeFromCode(code) {
  switch (code) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    default:
      return ;
  }
}

function statusCodeToCode(sc) {
  switch (sc) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    
  }
}

function statusCodeIsOk(sc) {
  if (sc === 0) {
    return true;
  } else {
    return false;
  }
}

function streamTypeIsClientStreaming(st) {
  switch (st) {
    case 0 :
    case 1 :
        return false;
    case 2 :
    case 3 :
        return true;
    
  }
}

function streamTypeIsServerStreaming(st) {
  switch (st) {
    case 0 :
    case 2 :
        return false;
    case 1 :
    case 3 :
        return true;
    
  }
}

function compressionAsStr(c) {
  switch (c) {
    case 0 :
        return "identity";
    case 1 :
        return "gzip";
    case 2 :
        return "deflate";
    case 3 :
        return "snappy";
    case 4 :
        return "zstd";
    
  }
}

function grpcContentTypeHeader(ct) {
  if (ct === 0) {
    return "application/grpc+proto";
  } else {
    return "application/grpc+json";
  }
}

function streamStateFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    default:
      return ;
  }
}

function streamStateToTag(ss) {
  switch (ss) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    
  }
}

function streamCanSendData(ss) {
  switch (ss) {
    case 1 :
    case 3 :
        return true;
    default:
      return false;
  }
}

function streamCanReceiveData(ss) {
  switch (ss) {
    case 1 :
    case 2 :
        return true;
    default:
      return false;
  }
}

function streamCanUpdateWindow(ss) {
  switch (ss) {
    case 0 :
    case 4 :
    case 5 :
        return false;
    default:
      return true;
  }
}

function streamIsTerminal(ss) {
  if (ss === 5) {
    return true;
  } else {
    return false;
  }
}

function validateStreamTransition(from, to) {
  switch (from) {
    case 0 :
        switch (to) {
          case 1 :
              return "SendHeaders";
          case 4 :
              return "PushPromiseRecv";
          default:
            return ;
        }
    case 1 :
        switch (to) {
          case 2 :
              return "LocalEndStream";
          case 3 :
              return "RemoteEndStream";
          case 5 :
              return "ResetFromOpen";
          default:
            return ;
        }
    case 2 :
        if (to === 5) {
          return "CloseHalfLocal";
        } else {
          return ;
        }
    case 3 :
        if (to === 5) {
          return "CloseHalfRemote";
        } else {
          return ;
        }
    case 4 :
        switch (to) {
          case 3 :
              return "ReservedToHalf";
          case 5 :
              return "ReservedReset";
          default:
            return ;
        }
    case 5 :
        return ;
    
  }
}

export {
  statusCodeFromCode ,
  statusCodeToCode ,
  statusCodeIsOk ,
  streamTypeIsClientStreaming ,
  streamTypeIsServerStreaming ,
  compressionAsStr ,
  grpcContentTypeHeader ,
  streamStateFromTag ,
  streamStateToTag ,
  streamCanSendData ,
  streamCanReceiveData ,
  streamCanUpdateWindow ,
  streamIsTerminal ,
  validateStreamTransition ,
}
/* No side effect */
