// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

var allRecordTypes = [
  1,
  2,
  5,
  6,
  12,
  15,
  16,
  28,
  33
];

function recordTypeFromTypeCode(code) {
  switch (code) {
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 12 :
        return 12;
    case 15 :
        return 15;
    case 16 :
        return 16;
    case 28 :
        return 28;
    case 33 :
        return 33;
    default:
      return ;
  }
}

function recordTypeToTypeCode(rt) {
  switch (rt) {
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 12 :
        return 12;
    case 15 :
        return 15;
    case 16 :
        return 16;
    case 28 :
        return 28;
    case 33 :
        return 33;
    
  }
}

function recordTypeMnemonic(rt) {
  switch (rt) {
    case 1 :
        return "A";
    case 2 :
        return "NS";
    case 5 :
        return "CNAME";
    case 6 :
        return "SOA";
    case 12 :
        return "PTR";
    case 15 :
        return "MX";
    case 16 :
        return "TXT";
    case 28 :
        return "AAAA";
    case 33 :
        return "SRV";
    
  }
}

function recordTypeIsAddress(rt) {
  switch (rt) {
    case 1 :
    case 28 :
        return true;
    default:
      return false;
  }
}

function recordTypeIsInfrastructure(rt) {
  switch (rt) {
    case 2 :
    case 6 :
        return true;
    default:
      return false;
  }
}

function responseCodeFromRcode(code) {
  switch (code) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    default:
      return ;
  }
}

function responseCodeToRcode(rc) {
  switch (rc) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    
  }
}

function responseCodeIsSuccess(rc) {
  if (rc === 0) {
    return true;
  } else {
    return false;
  }
}

function responseCodeIsNxdomain(rc) {
  if (rc === 3) {
    return true;
  } else {
    return false;
  }
}

function responseCodeAsStr(rc) {
  switch (rc) {
    case 0 :
        return "NOERROR";
    case 1 :
        return "FORMERR";
    case 2 :
        return "SERVFAIL";
    case 3 :
        return "NXDOMAIN";
    case 4 :
        return "NOTIMP";
    case 5 :
        return "REFUSED";
    
  }
}

function validateDomainName(name) {
  var len = name.length;
  if (len === 0) {
    return {
            TAG: "Error",
            _0: "EmptyName"
          };
  }
  if (len > 253) {
    return {
            TAG: "Error",
            _0: {
              TAG: "NameTooLong",
              name: name,
              length: len
            }
          };
  }
  var labels = name.split(".");
  var numLabels = labels.length;
  var _idx = 0;
  while(true) {
    var idx = _idx;
    if (idx >= numLabels) {
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
    var label = Belt_Array.getExn(labels, idx);
    var labelLen = label.length;
    if (labelLen === 0) {
      return {
              TAG: "Error",
              _0: "EmptyLabel"
            };
    }
    if (labelLen > 63) {
      return {
              TAG: "Error",
              _0: {
                TAG: "LabelTooLong",
                label: label,
                length: labelLen
              }
            };
    }
    _idx = idx + 1 | 0;
    continue ;
  };
}

var dnsPort = 53;

var maxUdpSize = 512;

var maxTcpSize = 65535;

var maxLabelLength = 63;

var maxNameLength = 253;

var ednsUdpSize = 4096;

export {
  dnsPort ,
  maxUdpSize ,
  maxTcpSize ,
  maxLabelLength ,
  maxNameLength ,
  ednsUdpSize ,
  allRecordTypes ,
  recordTypeFromTypeCode ,
  recordTypeToTypeCode ,
  recordTypeMnemonic ,
  recordTypeIsAddress ,
  recordTypeIsInfrastructure ,
  responseCodeFromRcode ,
  responseCodeToRcode ,
  responseCodeIsSuccess ,
  responseCodeIsNxdomain ,
  responseCodeAsStr ,
  validateDomainName ,
}
/* No side effect */
