// Generated by ReScript, PLEASE EDIT WITH CARE


function opcodeFromNibble(nibble) {
  switch (nibble) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    default:
      return ;
  }
}

function opcodeToNibble(op) {
  switch (op) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    
  }
}

function opcodeIsData(op) {
  switch (op) {
    case 0 :
    case 1 :
    case 2 :
        return true;
    default:
      return false;
  }
}

function opcodeIsControl(op) {
  return !opcodeIsData(op);
}

function opcodeIsMessageStart(op) {
  switch (op) {
    case 1 :
    case 2 :
        return true;
    default:
      return false;
  }
}

function opcodeRequiresResponse(op) {
  switch (op) {
    case 8 :
    case 9 :
        return true;
    default:
      return false;
  }
}

function opcodeName(op) {
  switch (op) {
    case 0 :
        return "continuation";
    case 1 :
        return "text";
    case 2 :
        return "binary";
    case 8 :
        return "close";
    case 9 :
        return "ping";
    case 10 :
        return "pong";
    
  }
}

function closeCodeFromWire(code) {
  switch (code) {
    case 1000 :
        return 1000;
    case 1001 :
        return 1001;
    case 1002 :
        return 1002;
    case 1003 :
        return 1003;
    case 1005 :
        return 1005;
    case 1006 :
        return 1006;
    case 1007 :
        return 1007;
    case 1008 :
        return 1008;
    case 1009 :
        return 1009;
    case 1010 :
        return 1010;
    case 1011 :
        return 1011;
    default:
      return ;
  }
}

function closeCodeToWire(cc) {
  switch (cc) {
    case 1000 :
        return 1000;
    case 1001 :
        return 1001;
    case 1002 :
        return 1002;
    case 1003 :
        return 1003;
    case 1005 :
        return 1005;
    case 1006 :
        return 1006;
    case 1007 :
        return 1007;
    case 1008 :
        return 1008;
    case 1009 :
        return 1009;
    case 1010 :
        return 1010;
    case 1011 :
        return 1011;
    
  }
}

function closeCodeIsNormal(cc) {
  switch (cc) {
    case 1000 :
    case 1001 :
        return true;
    default:
      return false;
  }
}

function closeCodeIsError(cc) {
  switch (cc) {
    case 1000 :
    case 1001 :
    case 1005 :
        return false;
    default:
      return true;
  }
}

function closeCodeIsSendable(cc) {
  switch (cc) {
    case 1005 :
    case 1006 :
        return false;
    default:
      return true;
  }
}

function closeCodeReason(cc) {
  switch (cc) {
    case 1000 :
        return "Normal closure";
    case 1001 :
        return "Endpoint going away";
    case 1002 :
        return "Protocol error";
    case 1003 :
        return "Unsupported data type";
    case 1005 :
        return "No status code present";
    case 1006 :
        return "Abnormal closure (no close frame)";
    case 1007 :
        return "Invalid payload data";
    case 1008 :
        return "Policy violation";
    case 1009 :
        return "Message too big";
    case 1010 :
        return "Mandatory extension missing";
    case 1011 :
        return "Internal server error";
    
  }
}

function isApplicationCode(code) {
  if (code >= 4000) {
    return code <= 4999;
  } else {
    return false;
  }
}

function isPrivateCode(code) {
  if (code >= 3000) {
    return code <= 3999;
  } else {
    return false;
  }
}

function validateFrameCommon(f, maxFrameSize) {
  if (!opcodeIsData(f.opcode) && f.payloadLength > 125) {
    return {
            TAG: "ControlFrameTooLarge",
            opcode: f.opcode,
            size: f.payloadLength
          };
  } else if (!opcodeIsData(f.opcode) && !f.fin) {
    return {
            TAG: "ControlFrameFragmented",
            opcode: f.opcode
          };
  } else if (f.payloadLength > maxFrameSize) {
    return {
            TAG: "PayloadTooLarge",
            size: f.payloadLength,
            maxSize: maxFrameSize
          };
  } else if (f.payloadLength !== f.payload.length) {
    return {
            TAG: "PayloadLengthMismatch",
            declared: f.payloadLength,
            actual: f.payload.length
          };
  } else {
    return ;
  }
}

function validateClientFrame(f, maxFrameSize) {
  if (f.masked) {
    return validateFrameCommon(f, maxFrameSize);
  } else {
    return "ClientFrameNotMasked";
  }
}

function validateServerFrame(f, maxFrameSize) {
  if (f.masked) {
    return "ServerFrameMasked";
  } else {
    return validateFrameCommon(f, maxFrameSize);
  }
}

function makeTextFrame(payload) {
  return {
          fin: true,
          opcode: 1,
          masked: false,
          payloadLength: payload.length,
          maskingKey: undefined,
          payload: payload
        };
}

function makeBinaryFrame(payload) {
  return {
          fin: true,
          opcode: 2,
          masked: false,
          payloadLength: payload.length,
          maskingKey: undefined,
          payload: payload
        };
}

function makePongFrame(pingPayload) {
  return {
          fin: true,
          opcode: 10,
          masked: false,
          payloadLength: pingPayload.length,
          maskingKey: undefined,
          payload: pingPayload
        };
}

function makePingFrame(payload) {
  return {
          fin: true,
          opcode: 9,
          masked: false,
          payloadLength: payload.length,
          maskingKey: undefined,
          payload: payload
        };
}

var maxControlPayload = 125;

export {
  opcodeFromNibble ,
  opcodeToNibble ,
  opcodeIsData ,
  opcodeIsControl ,
  opcodeIsMessageStart ,
  opcodeRequiresResponse ,
  opcodeName ,
  closeCodeFromWire ,
  closeCodeToWire ,
  closeCodeIsNormal ,
  closeCodeIsError ,
  closeCodeIsSendable ,
  closeCodeReason ,
  isApplicationCode ,
  isPrivateCode ,
  maxControlPayload ,
  validateFrameCommon ,
  validateClientFrame ,
  validateServerFrame ,
  makeTextFrame ,
  makeBinaryFrame ,
  makePongFrame ,
  makePingFrame ,
}
/* No side effect */
