// Generated by ReScript, PLEASE EDIT WITH CARE


function operationTypeFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    default:
      return ;
  }
}

function operationTypeToTag(op) {
  switch (op) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    
  }
}

function operationTypeAsStr(op) {
  switch (op) {
    case 0 :
        return "query";
    case 1 :
        return "mutation";
    case 2 :
        return "subscription";
    
  }
}

function typeKindFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    default:
      return ;
  }
}

function typeKindToTag(tk) {
  switch (tk) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    
  }
}

function typeKindIntrospectionName(tk) {
  switch (tk) {
    case 0 :
        return "SCALAR";
    case 1 :
        return "OBJECT";
    case 2 :
        return "INTERFACE";
    case 3 :
        return "UNION";
    case 4 :
        return "ENUM";
    case 5 :
        return "INPUT_OBJECT";
    case 6 :
        return "LIST";
    case 7 :
        return "NON_NULL";
    
  }
}

function typeKindIsWrapper(tk) {
  switch (tk) {
    case 6 :
    case 7 :
        return true;
    default:
      return false;
  }
}

function typeKindIsComposite(tk) {
  switch (tk) {
    case 1 :
    case 2 :
    case 3 :
        return true;
    default:
      return false;
  }
}

function directiveLocationFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    case 17 :
        return 17;
    default:
      return ;
  }
}

function directiveLocationToTag(loc) {
  switch (loc) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    case 17 :
        return 17;
    
  }
}

function directiveLocationIsExecutable(loc) {
  return directiveLocationToTag(loc) <= 6;
}

function directiveLocationIsTypeSystem(loc) {
  return !directiveLocationIsExecutable(loc);
}

function directiveLocationAsStr(loc) {
  switch (loc) {
    case 0 :
        return "QUERY";
    case 1 :
        return "MUTATION";
    case 2 :
        return "SUBSCRIPTION";
    case 3 :
        return "FIELD";
    case 4 :
        return "FRAGMENT_DEFINITION";
    case 5 :
        return "FRAGMENT_SPREAD";
    case 6 :
        return "INLINE_FRAGMENT";
    case 7 :
        return "SCHEMA";
    case 8 :
        return "SCALAR";
    case 9 :
        return "OBJECT";
    case 10 :
        return "FIELD_DEFINITION";
    case 11 :
        return "ARGUMENT_DEFINITION";
    case 12 :
        return "INTERFACE";
    case 13 :
        return "UNION";
    case 14 :
        return "ENUM";
    case 15 :
        return "ENUM_VALUE";
    case 16 :
        return "INPUT_OBJECT";
    case 17 :
        return "INPUT_FIELD_DEFINITION";
    
  }
}

function errorCategoryFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    default:
      return ;
  }
}

function errorCategoryToTag(ec) {
  switch (ec) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    
  }
}

function errorCategoryCode(ec) {
  switch (ec) {
    case 0 :
        return "PARSE_ERROR";
    case 1 :
        return "VALIDATION_ERROR";
    case 2 :
        return "EXECUTION_ERROR";
    case 3 :
        return "AUTH_ERROR";
    case 4 :
        return "RATE_LIMITED";
    
  }
}

export {
  operationTypeFromTag ,
  operationTypeToTag ,
  operationTypeAsStr ,
  typeKindFromTag ,
  typeKindToTag ,
  typeKindIntrospectionName ,
  typeKindIsWrapper ,
  typeKindIsComposite ,
  directiveLocationFromTag ,
  directiveLocationToTag ,
  directiveLocationIsExecutable ,
  directiveLocationIsTypeSystem ,
  directiveLocationAsStr ,
  errorCategoryFromTag ,
  errorCategoryToTag ,
  errorCategoryCode ,
}
/* No side effect */
