// Generated by ReScript, PLEASE EDIT WITH CARE


var allMethods = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8
];

function methodParse(s) {
  switch (s) {
    case "CONNECT" :
        return 8;
    case "DELETE" :
        return 3;
    case "GET" :
        return 0;
    case "HEAD" :
        return 5;
    case "OPTIONS" :
        return 6;
    case "PATCH" :
        return 4;
    case "POST" :
        return 1;
    case "PUT" :
        return 2;
    case "TRACE" :
        return 7;
    default:
      return ;
  }
}

function methodFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    default:
      return ;
  }
}

function methodToTag(m) {
  switch (m) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    
  }
}

function methodAsStr(m) {
  switch (m) {
    case 0 :
        return "GET";
    case 1 :
        return "POST";
    case 2 :
        return "PUT";
    case 3 :
        return "DELETE";
    case 4 :
        return "PATCH";
    case 5 :
        return "HEAD";
    case 6 :
        return "OPTIONS";
    case 7 :
        return "TRACE";
    case 8 :
        return "CONNECT";
    
  }
}

function methodIsSafe(m) {
  switch (m) {
    case 0 :
    case 5 :
    case 6 :
    case 7 :
        return true;
    default:
      return false;
  }
}

function methodIsIdempotent(m) {
  switch (m) {
    case 1 :
    case 4 :
    case 8 :
        return false;
    default:
      return true;
  }
}

function methodHasRequestBody(m) {
  switch (m) {
    case 1 :
    case 2 :
    case 4 :
        return true;
    default:
      return false;
  }
}

function versionFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    default:
      return ;
  }
}

function versionToTag(v) {
  switch (v) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    
  }
}

function versionAsStr(v) {
  switch (v) {
    case 0 :
        return "HTTP/1.0";
    case 1 :
        return "HTTP/1.1";
    case 2 :
        return "HTTP/2";
    case 3 :
        return "HTTP/3";
    
  }
}

function statusCategoryFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    default:
      return ;
  }
}

function statusCategoryToTag(c) {
  switch (c) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    
  }
}

function statusCodeFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    case 17 :
        return 17;
    case 18 :
        return 18;
    case 19 :
        return 19;
    case 20 :
        return 20;
    case 21 :
        return 21;
    case 22 :
        return 22;
    case 23 :
        return 23;
    case 24 :
        return 24;
    case 25 :
        return 25;
    case 26 :
        return 26;
    case 27 :
        return 27;
    case 28 :
        return 28;
    default:
      return ;
  }
}

function statusCodeToTag(s) {
  switch (s) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    case 17 :
        return 17;
    case 18 :
        return 18;
    case 19 :
        return 19;
    case 20 :
        return 20;
    case 21 :
        return 21;
    case 22 :
        return 22;
    case 23 :
        return 23;
    case 24 :
        return 24;
    case 25 :
        return 25;
    case 26 :
        return 26;
    case 27 :
        return 27;
    case 28 :
        return 28;
    
  }
}

function statusNumericCode(s) {
  switch (s) {
    case 0 :
        return 100;
    case 1 :
        return 101;
    case 2 :
        return 200;
    case 3 :
        return 201;
    case 4 :
        return 202;
    case 5 :
        return 204;
    case 6 :
        return 301;
    case 7 :
        return 302;
    case 8 :
        return 304;
    case 9 :
        return 307;
    case 10 :
        return 308;
    case 11 :
        return 400;
    case 12 :
        return 401;
    case 13 :
        return 403;
    case 14 :
        return 404;
    case 15 :
        return 405;
    case 16 :
        return 408;
    case 17 :
        return 409;
    case 18 :
        return 410;
    case 19 :
        return 411;
    case 20 :
        return 413;
    case 21 :
        return 414;
    case 22 :
        return 415;
    case 23 :
        return 429;
    case 24 :
        return 500;
    case 25 :
        return 501;
    case 26 :
        return 502;
    case 27 :
        return 503;
    case 28 :
        return 504;
    
  }
}

function statusFromNumeric(code) {
  if (code >= 301) {
    if (code < 430) {
      if (code >= 309) {
        if (code < 400) {
          return ;
        }
        switch (code) {
          case 400 :
              return 11;
          case 401 :
              return 12;
          case 403 :
              return 13;
          case 404 :
              return 14;
          case 405 :
              return 15;
          case 408 :
              return 16;
          case 409 :
              return 17;
          case 410 :
              return 18;
          case 411 :
              return 19;
          case 413 :
              return 20;
          case 414 :
              return 21;
          case 415 :
              return 22;
          case 402 :
          case 406 :
          case 407 :
          case 412 :
          case 416 :
          case 417 :
          case 418 :
          case 419 :
          case 420 :
          case 421 :
          case 422 :
          case 423 :
          case 424 :
          case 425 :
          case 426 :
          case 427 :
          case 428 :
              return ;
          case 429 :
              return 23;
          
        }
      } else {
        switch (code) {
          case 301 :
              return 6;
          case 302 :
              return 7;
          case 304 :
              return 8;
          case 303 :
          case 305 :
          case 306 :
              return ;
          case 307 :
              return 9;
          case 308 :
              return 10;
          
        }
      }
    } else {
      switch (code) {
        case 500 :
            return 24;
        case 501 :
            return 25;
        case 502 :
            return 26;
        case 503 :
            return 27;
        case 504 :
            return 28;
        default:
          return ;
      }
    }
  } else {
    if (code === 101 || code === 100) {
      if (code >= 101) {
        return 1;
      } else {
        return 0;
      }
    }
    switch (code) {
      case 200 :
          return 2;
      case 201 :
          return 3;
      case 202 :
          return 4;
      case 204 :
          return 5;
      default:
        return ;
    }
  }
}

function statusReasonPhrase(s) {
  switch (s) {
    case 0 :
        return "Continue";
    case 1 :
        return "Switching Protocols";
    case 2 :
        return "OK";
    case 3 :
        return "Created";
    case 4 :
        return "Accepted";
    case 5 :
        return "No Content";
    case 6 :
        return "Moved Permanently";
    case 7 :
        return "Found";
    case 8 :
        return "Not Modified";
    case 9 :
        return "Temporary Redirect";
    case 10 :
        return "Permanent Redirect";
    case 11 :
        return "Bad Request";
    case 12 :
        return "Unauthorized";
    case 13 :
        return "Forbidden";
    case 14 :
        return "Not Found";
    case 15 :
        return "Method Not Allowed";
    case 16 :
        return "Request Timeout";
    case 17 :
        return "Conflict";
    case 18 :
        return "Gone";
    case 19 :
        return "Length Required";
    case 20 :
        return "Payload Too Large";
    case 21 :
        return "URI Too Long";
    case 22 :
        return "Unsupported Media Type";
    case 23 :
        return "Too Many Requests";
    case 24 :
        return "Internal Server Error";
    case 25 :
        return "Not Implemented";
    case 26 :
        return "Bad Gateway";
    case 27 :
        return "Service Unavailable";
    case 28 :
        return "Gateway Timeout";
    
  }
}

function statusCategory(s) {
  var tag = statusCodeToTag(s);
  if (tag <= 1) {
    return 0;
  } else if (tag <= 5) {
    return 1;
  } else if (tag <= 10) {
    return 2;
  } else if (tag <= 23) {
    return 3;
  } else {
    return 4;
  }
}

function statusIsSuccess(s) {
  return statusCategory(s) === 1;
}

function statusIsError(s) {
  var match = statusCategory(s);
  switch (match) {
    case 3 :
    case 4 :
        return true;
    default:
      return false;
  }
}

function statusIsRedirect(s) {
  return statusCategory(s) === 2;
}

function contentTypeFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    default:
      return ;
  }
}

function contentTypeToTag(ct) {
  switch (ct) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    
  }
}

function contentTypeMime(ct) {
  switch (ct) {
    case 0 :
        return "text/plain";
    case 1 :
        return "text/html";
    case 2 :
        return "application/json";
    case 3 :
        return "application/xml";
    case 4 :
        return "application/x-www-form-urlencoded";
    case 5 :
        return "multipart/form-data";
    case 6 :
        return "application/octet-stream";
    case 7 :
        return "text/css";
    
  }
}

function headerTypeFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    default:
      return ;
  }
}

function headerTypeToTag(ht) {
  switch (ht) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    
  }
}

function headerTypeName(ht) {
  switch (ht) {
    case 0 :
        return "Content-Type";
    case 1 :
        return "Content-Length";
    case 2 :
        return "Host";
    case 3 :
        return "Connection";
    case 4 :
        return "Accept";
    case 5 :
        return "User-Agent";
    case 6 :
        return "Server";
    case 7 :
        return "Location";
    case 8 :
        return "Cache-Control";
    case 9 :
        return "X-Custom";
    
  }
}

function requestPhaseFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    default:
      return ;
  }
}

function requestPhaseToTag(p) {
  switch (p) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    
  }
}

function transitionFromPhase(t) {
  switch (t) {
    case "StartReceiving" :
        return 0;
    case "FinishSend" :
        return 5;
    case "KeepAliveRecycle" :
        return 6;
    case "ParseHeaders" :
    case "AbortReceiving" :
        return 1;
    case "BodyDone" :
    case "AbortBodyReceiving" :
        return 3;
    case "BeginResponse" :
    case "AbortComplete" :
        return 4;
    default:
      return 2;
  }
}

function transitionToPhase(t) {
  switch (t) {
    case "StartReceiving" :
        return 1;
    case "ParseHeaders" :
        return 2;
    case "StartBody" :
        return 3;
    case "NoBodyComplete" :
    case "BodyDone" :
        return 4;
    case "BeginResponse" :
        return 5;
    case "KeepAliveRecycle" :
        return 0;
    default:
      return 6;
  }
}

function validateHttpTransition(from, to) {
  switch (from) {
    case 0 :
        if (to === 1) {
          return "StartReceiving";
        } else {
          return ;
        }
    case 1 :
        switch (to) {
          case 2 :
              return "ParseHeaders";
          case 6 :
              return "AbortReceiving";
          default:
            return ;
        }
    case 2 :
        switch (to) {
          case 3 :
              return "StartBody";
          case 4 :
              return "NoBodyComplete";
          case 6 :
              return "AbortHeadersParsed";
          default:
            return ;
        }
    case 3 :
        switch (to) {
          case 4 :
              return "BodyDone";
          case 6 :
              return "AbortBodyReceiving";
          default:
            return ;
        }
    case 4 :
        switch (to) {
          case 5 :
              return "BeginResponse";
          case 6 :
              return "AbortComplete";
          default:
            return ;
        }
    case 5 :
        if (to === 6) {
          return "FinishSend";
        } else {
          return ;
        }
    case 6 :
        if (to === 0) {
          return "KeepAliveRecycle";
        } else {
          return ;
        }
    
  }
}

export {
  allMethods ,
  methodParse ,
  methodFromTag ,
  methodToTag ,
  methodAsStr ,
  methodIsSafe ,
  methodIsIdempotent ,
  methodHasRequestBody ,
  versionFromTag ,
  versionToTag ,
  versionAsStr ,
  statusCategoryFromTag ,
  statusCategoryToTag ,
  statusCodeFromTag ,
  statusCodeToTag ,
  statusNumericCode ,
  statusFromNumeric ,
  statusReasonPhrase ,
  statusCategory ,
  statusIsSuccess ,
  statusIsError ,
  statusIsRedirect ,
  contentTypeFromTag ,
  contentTypeToTag ,
  contentTypeMime ,
  headerTypeFromTag ,
  headerTypeToTag ,
  headerTypeName ,
  requestPhaseFromTag ,
  requestPhaseToTag ,
  transitionFromPhase ,
  transitionToPhase ,
  validateHttpTransition ,
}
/* No side effect */
