// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Proven_servers from "proven_servers";

function init() {
  var handle = Proven_servers.proven_servers_init();
  if (handle == null) {
    return {
            TAG: "Error",
            _0: {
              TAG: "InitError",
              _0: "proven_servers_init returned null"
            }
          };
  } else {
    return {
            TAG: "Ok",
            _0: handle
          };
  }
}

function free(handle) {
  Proven_servers.proven_servers_free(handle);
}

function isInitialized(handle) {
  return Proven_servers.proven_servers_is_initialized(handle) !== 0;
}

function version() {
  return Proven_servers.proven_servers_version();
}

function buildInfo() {
  return Proven_servers.proven_servers_build_info();
}

function lastError() {
  return Caml_option.nullable_to_opt(Proven_servers.proven_servers_last_error());
}

var allProtocols = [
  "Httpd",
  "Dns",
  "Smtp",
  "Ftp",
  "SshBastion",
  "Mqtt",
  "Grpc",
  "Graphql",
  "Tls",
  "Firewall",
  "Websocket"
];

var boundProtocolCount = 11;

var totalProtocolCount = 98;

export {
  init ,
  free ,
  isInitialized ,
  version ,
  buildInfo ,
  lastError ,
  allProtocols ,
  boundProtocolCount ,
  totalProtocolCount ,
}
/* proven_servers Not a pure module */
