// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ProvenCore from "./ProvenCore.res.mjs";

function protocolAsStr(p) {
  if (typeof p === "object") {
    return p._0;
  }
  switch (p) {
    case "Httpd" :
        return "httpd";
    case "Dns" :
        return "dns";
    case "Smtp" :
        return "smtp";
    case "Ftp" :
        return "ftp";
    case "SshBastion" :
        return "ssh-bastion";
    case "Mqtt" :
        return "mqtt";
    case "Grpc" :
        return "grpc";
    case "Graphql" :
        return "graphql";
    case "Tls" :
        return "tls";
    case "Firewall" :
        return "firewall";
    case "Websocket" :
        return "websocket";
    
  }
}

function fromResultCode(code) {
  return {
          TAG: "FfiError",
          code: code,
          message: ProvenCore.resultDescription(code)
        };
}

function unknownTag(proto, typeName, rawTag) {
  return {
          TAG: "DecodeError",
          protocol: proto,
          typeName: typeName,
          rawTag: rawTag
        };
}

function invalidTransition(proto, fromState, toState) {
  return {
          TAG: "TransitionError",
          protocol: proto,
          fromState: fromState,
          toState: toState
        };
}

function describe(err) {
  switch (err.TAG) {
    case "FfiError" :
        return "FFI error (code " + String(ProvenCore.resultCodeToTag(err.code)) + "): " + err.message;
    case "HandleError" :
        return "Handle error: " + err._0;
    case "DecodeError" :
        return "Decode error in " + protocolAsStr(err.protocol) + ": unknown " + err.typeName + " tag " + String(err.rawTag);
    case "TransitionError" :
        return "Invalid transition in " + protocolAsStr(err.protocol) + ": " + err.fromState + " -> " + err.toState;
    case "InitError" :
        return "Initialisation error: " + err._0;
    case "UnsupportedError" :
        return "Unsupported: " + err._0;
    case "UnknownError" :
        return "Unknown error: " + err._0;
    
  }
}

function isRecoverable(err) {
  switch (err.TAG) {
    case "FfiError" :
        if (err.code === 1) {
          return true;
        } else {
          return false;
        }
    case "DecodeError" :
    case "TransitionError" :
        return true;
    default:
      return false;
  }
}

export {
  protocolAsStr ,
  fromResultCode ,
  unknownTag ,
  invalidTransition ,
  describe ,
  isRecoverable ,
}
/* No side effect */
