// Generated by ReScript, PLEASE EDIT WITH CARE


function commandTagFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    default:
      return ;
  }
}

function commandTagToTag(cmd) {
  switch (cmd) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    
  }
}

function commandTagVerb(cmd) {
  switch (cmd) {
    case 0 :
        return "HELO";
    case 1 :
        return "EHLO";
    case 2 :
        return "MAIL";
    case 3 :
        return "RCPT";
    case 4 :
        return "DATA";
    case 5 :
        return "QUIT";
    case 6 :
        return "RSET";
    case 7 :
        return "NOOP";
    case 8 :
        return "VRFY";
    case 9 :
        return "EXPN";
    case 10 :
        return "STARTTLS";
    case 11 :
        return "AUTH";
    
  }
}

function commandTagRequiresSession(cmd) {
  switch (cmd) {
    case 0 :
    case 1 :
    case 5 :
    case 6 :
    case 7 :
        return false;
    default:
      return true;
  }
}

function commandTagResetsTransaction(cmd) {
  switch (cmd) {
    case 0 :
    case 1 :
    case 6 :
        return true;
    default:
      return false;
  }
}

function replyCategoryFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    default:
      return ;
  }
}

function replyCategoryToTag(cat) {
  switch (cat) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    
  }
}

function replyCategoryAsStr(cat) {
  switch (cat) {
    case 0 :
        return "Positive";
    case 1 :
        return "Intermediate";
    case 2 :
        return "TransientNegative";
    case 3 :
        return "PermanentNegative";
    
  }
}

function replyCodeFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    default:
      return ;
  }
}

function replyCodeToTag(code) {
  switch (code) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    case 16 :
        return 16;
    
  }
}

function replyNumericCode(code) {
  switch (code) {
    case 0 :
        return 220;
    case 1 :
        return 221;
    case 2 :
        return 250;
    case 3 :
        return 251;
    case 4 :
        return 354;
    case 5 :
        return 421;
    case 6 :
        return 450;
    case 7 :
        return 451;
    case 8 :
        return 452;
    case 9 :
        return 500;
    case 10 :
        return 501;
    case 11 :
        return 502;
    case 12 :
        return 503;
    case 13 :
        return 504;
    case 14 :
        return 550;
    case 15 :
        return 553;
    case 16 :
        return 554;
    
  }
}

function replyDefaultMessage(code) {
  switch (code) {
    case 0 :
        return "Service ready";
    case 1 :
        return "Service closing transmission channel";
    case 2 :
        return "OK";
    case 3 :
        return "User not local; will forward";
    case 4 :
        return "Start mail input; end with <CRLF>.<CRLF>";
    case 5 :
        return "Service not available";
    case 6 :
        return "Mailbox busy";
    case 7 :
        return "Local error in processing";
    case 8 :
        return "Insufficient system storage";
    case 9 :
        return "Syntax error, command unrecognised";
    case 10 :
        return "Syntax error in parameters";
    case 11 :
        return "Command not implemented";
    case 12 :
        return "Bad sequence of commands";
    case 13 :
        return "Command parameter not implemented";
    case 14 :
        return "Mailbox unavailable";
    case 15 :
        return "Mailbox name not allowed";
    case 16 :
        return "Transaction failed";
    
  }
}

function replyCategory(code) {
  var tag = replyCodeToTag(code);
  if (tag <= 3) {
    return 0;
  } else if (tag === 4) {
    return 1;
  } else if (tag <= 8) {
    return 2;
  } else {
    return 3;
  }
}

function replyIsPositive(code) {
  return replyCategory(code) === 0;
}

function replyIsPermanentError(code) {
  return replyCategory(code) === 3;
}

function replyIsTransientError(code) {
  return replyCategory(code) === 2;
}

function authMechanismFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    default:
      return ;
  }
}

function authMechanismToTag(mech) {
  switch (mech) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    
  }
}

function authMechanismAsStr(mech) {
  switch (mech) {
    case 0 :
        return "PLAIN";
    case 1 :
        return "LOGIN";
    case 2 :
        return "CRAM-MD5";
    case 3 :
        return "XOAUTH2";
    
  }
}

function smtpExtensionFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    default:
      return ;
  }
}

function smtpExtensionToTag(ext) {
  switch (ext) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    
  }
}

function smtpExtensionKeyword(ext) {
  switch (ext) {
    case 0 :
        return "SIZE";
    case 1 :
        return "PIPELINING";
    case 2 :
        return "8BITMIME";
    case 3 :
        return "STARTTLS";
    case 4 :
        return "AUTH";
    case 5 :
        return "DSN";
    case 6 :
        return "CHUNKING";
    
  }
}

function sessionStateFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    default:
      return ;
  }
}

function sessionStateToTag(s) {
  switch (s) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    
  }
}

function sessionStateIsTerminal(s) {
  if (s === 8) {
    return true;
  } else {
    return false;
  }
}

function validateSessionTransition(from, to) {
  switch (from) {
    case 0 :
        switch (to) {
          case 1 :
              return "Greet";
          case 8 :
              return "QuitFromConnected";
          default:
            return ;
        }
    case 1 :
        switch (to) {
          case 2 :
              return "StartAuth";
          case 4 :
              return "RelayMailFrom";
          case 8 :
              return "QuitFromGreeted";
          default:
            return ;
        }
    case 2 :
        switch (to) {
          case 1 :
              return "AuthFailure";
          case 3 :
              return "AuthSuccess";
          default:
            return ;
        }
    case 3 :
        switch (to) {
          case 4 :
              return "AuthMailFrom";
          case 8 :
              return "QuitFromAuth";
          default:
            return ;
        }
    case 4 :
        switch (to) {
          case 1 :
              return "ResetFromMailFrom";
          case 5 :
              return "AddRecipient";
          case 8 :
              return "QuitFromMailFrom";
          default:
            return ;
        }
    case 5 :
        switch (to) {
          case 1 :
              return "ResetFromRcptTo";
          case 5 :
              return "AddMoreRecipients";
          case 6 :
              return "BeginData";
          case 8 :
              return "QuitFromRcptTo";
          default:
            return ;
        }
    case 6 :
        if (to === 7) {
          return "FinishData";
        } else {
          return ;
        }
    case 7 :
        switch (to) {
          case 1 :
              return "ResetToGreeted";
          case 3 :
              return "ResetToAuth";
          case 8 :
              return "QuitFromMsgRecv";
          default:
            return ;
        }
    case 8 :
        return ;
    
  }
}

var smtpPort = 25;

var submissionPort = 587;

var smtpsPort = 465;

var maxCommandLineLength = 512;

var maxReplyLineLength = 512;

var maxTextLineLength = 998;

export {
  commandTagFromTag ,
  commandTagToTag ,
  commandTagVerb ,
  commandTagRequiresSession ,
  commandTagResetsTransaction ,
  replyCategoryFromTag ,
  replyCategoryToTag ,
  replyCategoryAsStr ,
  replyCodeFromTag ,
  replyCodeToTag ,
  replyNumericCode ,
  replyDefaultMessage ,
  replyCategory ,
  replyIsPositive ,
  replyIsPermanentError ,
  replyIsTransientError ,
  authMechanismFromTag ,
  authMechanismToTag ,
  authMechanismAsStr ,
  smtpExtensionFromTag ,
  smtpExtensionToTag ,
  smtpExtensionKeyword ,
  sessionStateFromTag ,
  sessionStateToTag ,
  sessionStateIsTerminal ,
  validateSessionTransition ,
  smtpPort ,
  submissionPort ,
  smtpsPort ,
  maxCommandLineLength ,
  maxReplyLineLength ,
  maxTextLineLength ,
}
/* No side effect */
