// Generated by ReScript, PLEASE EDIT WITH CARE


function qosFromCode(code) {
  switch (code) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    default:
      return ;
  }
}

function qosToCode(q) {
  switch (q) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    
  }
}

function qosRequiresAck(q) {
  switch (q) {
    case 0 :
        return false;
    case 1 :
    case 2 :
        return true;
    
  }
}

function qosAckPacketCount(q) {
  switch (q) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 3;
    
  }
}

function qosEffective(requested, granted) {
  var reqCode = qosToCode(requested);
  var grantCode = qosToCode(granted);
  var minCode = reqCode < grantCode ? reqCode : grantCode;
  var q = qosFromCode(minCode);
  if (q !== undefined) {
    return q;
  } else {
    return 0;
  }
}

function qosDelivery(messageQos, subscriptionMax) {
  return qosEffective(messageQos, subscriptionMax);
}

function qosAsStr(q) {
  switch (q) {
    case 0 :
        return "QoS 0 (At Most Once)";
    case 1 :
        return "QoS 1 (At Least Once)";
    case 2 :
        return "QoS 2 (Exactly Once)";
    
  }
}

function subAckCodeFromByte($$byte) {
  if ($$byte >= 3) {
    if ($$byte !== 128) {
      return ;
    } else {
      return 128;
    }
  }
  if ($$byte < 0) {
    return ;
  }
  switch ($$byte) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    
  }
}

function subAckCodeToByte(code) {
  switch (code) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 128 :
        return 128;
    
  }
}

function subAckCodeToQos(code) {
  switch (code) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 128 :
        return ;
    
  }
}

function packetTypeFromCode(code) {
  switch (code) {
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    default:
      return ;
  }
}

function packetTypeToCode(pt) {
  switch (pt) {
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    case 5 :
        return 5;
    case 6 :
        return 6;
    case 7 :
        return 7;
    case 8 :
        return 8;
    case 9 :
        return 9;
    case 10 :
        return 10;
    case 11 :
        return 11;
    case 12 :
        return 12;
    case 13 :
        return 13;
    case 14 :
        return 14;
    case 15 :
        return 15;
    
  }
}

function packetTypeDirection(pt) {
  switch (pt) {
    case 2 :
    case 9 :
    case 11 :
    case 13 :
        return 1;
    case 1 :
    case 8 :
    case 10 :
    case 12 :
    case 14 :
        return 0;
    default:
      return 2;
  }
}

function packetTypeRequiresPacketId(pt) {
  switch (pt) {
    case 1 :
    case 2 :
    case 3 :
    case 12 :
    case 13 :
    case 14 :
    case 15 :
        return false;
    default:
      return true;
  }
}

function packetDirectionAsStr(d) {
  switch (d) {
    case 0 :
        return "Client->Server";
    case 1 :
        return "Server->Client";
    case 2 :
        return "Bidirectional";
    
  }
}

export {
  qosFromCode ,
  qosToCode ,
  qosRequiresAck ,
  qosAckPacketCount ,
  qosEffective ,
  qosDelivery ,
  qosAsStr ,
  subAckCodeFromByte ,
  subAckCodeToByte ,
  subAckCodeToQos ,
  packetTypeFromCode ,
  packetTypeToCode ,
  packetTypeDirection ,
  packetTypeRequiresPacketId ,
  packetDirectionAsStr ,
}
/* No side effect */
