// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function resultCodeFromTag(tag) {
  switch (tag) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    default:
      return ;
  }
}

function resultCodeToTag(code) {
  switch (code) {
    case 0 :
        return 0;
    case 1 :
        return 1;
    case 2 :
        return 2;
    case 3 :
        return 3;
    case 4 :
        return 4;
    
  }
}

function resultIsOk(code) {
  if (code === 0) {
    return true;
  } else {
    return false;
  }
}

function resultIsError(code) {
  return !resultIsOk(code);
}

function resultDescription(code) {
  switch (code) {
    case 0 :
        return "Success";
    case 1 :
        return "Generic error";
    case 2 :
        return "Invalid parameter";
    case 3 :
        return "Out of memory";
    case 4 :
        return "Null pointer";
    
  }
}

function platformPtrSizeBits(p) {
  if (p === 4) {
    return 32;
  } else {
    return 64;
  }
}

function platformPtrSizeBytes(p) {
  return platformPtrSizeBits(p) / 8 | 0;
}

function handleNew(ptr) {
  if (ptr === 0.0) {
    return ;
  } else {
    return {
            TAG: "Handle",
            _0: ptr
          };
  }
}

function handleAsPtr(h) {
  return h._0;
}

function paddingFor(offset, alignment) {
  if (alignment === 0) {
    return 0;
  }
  var remainder = Caml_int32.mod_(offset, alignment);
  if (remainder === 0) {
    return 0;
  } else {
    return alignment - remainder | 0;
  }
}

function alignUp(size, alignment) {
  return size + paddingFor(size, alignment) | 0;
}

export {
  resultCodeFromTag ,
  resultCodeToTag ,
  resultIsOk ,
  resultIsError ,
  resultDescription ,
  platformPtrSizeBits ,
  platformPtrSizeBytes ,
  handleNew ,
  handleAsPtr ,
  paddingFor ,
  alignUp ,
}
/* No side effect */
